# SpiceDB Operator HelmRelease
# ============================
#
# Deploys the SpiceDB operator via Helm using values from apps/spicedb/.
# The operator manages SpiceDBCluster custom resources, handling the
# deployment and lifecycle of SpiceDB authorization service instances.
#
# Chart: spicedb/spicedb-operator
# Version: 2.2.0
# Namespace: spicedb
#
# Features:
#   - SpiceDBCluster CRD management
#   - Automatic SpiceDB deployment and scaling
#   - PostgreSQL datastore integration
#   - gRPC API lifecycle management
#
# SpiceDB Clusters:
#   After operator deployment, create SpiceDBCluster resources in the
#   spicedb namespace. The operator will provision SpiceDB pods that
#   connect to the PostgreSQL datastore (CloudNativePG cluster).
#
# Dependencies:
#   - CloudNativePG operator (Phase 11) - for PostgreSQL datastore
#   - Cilium CNI (Phase 6) - networking for SpiceDB pods
#   - Proxmox CSI (Phase 7) - storage for PostgreSQL volumes
#
# IMPORTANT: This HelmRelease only deploys the operator. The actual
# SpiceDB cluster is created via SpiceDBCluster CRD in apps/spicedb/.
#
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spicedb-operator
  namespace: spicedb
spec:
  # Reference the SpiceDB operator Helm repository
  chart:
    spec:
      chart: spicedb-operator
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: spicedb-operator
        namespace: flux-system

  # Reconcile Helm release hourly (stable component)
  interval: 1h

  # Use Helm values from the ConfigMap generated by kustomization.yaml
  valuesFrom:
    - kind: ConfigMap
      name: spicedb-operator-values
      valuesKey: values.yaml

  # Install configuration
  install:
    # Create namespace if it doesn't exist
    createNamespace: true

    # Install CRDs via Helm (CreateReplace to update existing)
    crds: CreateReplace

    # Remediation on install failure
    remediation:
      retries: 3

  # Upgrade configuration
  upgrade:
    # Clean up old resources on upgrade
    cleanupOnFail: true

    # Upgrade CRDs
    crds: CreateReplace

    # Remediation on upgrade failure
    remediation:
      retries: 3
      # Rollback on upgrade failure
      remediateLastFailure: true

  # Rollback configuration
  rollback:
    cleanupOnFail: true

  # Wait for all resources to be ready
  timeout: 10m

  # Dependencies - ensure CloudNativePG operator is ready
  # SpiceDB requires PostgreSQL operator for its datastore
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
