# SpiceDB Kustomization
# =====================
#
# Applies the SpiceDB configuration from apps/spicedb/.
# This Kustomization generates the ConfigMap with Helm values
# that the HelmRelease references, and deploys all SpiceDB resources:
#
#   - Namespace
#   - PostgreSQL cluster (CloudNativePG)
#   - SpiceDB configuration Secret (template - requires manual creation)
#   - SpiceDBCluster custom resource
#
# Dependency Chain:
#   1. infrastructure (all infrastructure components ready)
#   2. spicedb-operator (HelmRelease) - operator must be running
#   3. This Kustomization (SpiceDB application resources)
#
# Resource Creation Order:
#   1. Namespace created first
#   2. PostgreSQL cluster provisioned (CloudNativePG)
#   3. Secret must be manually created with actual values
#   4. SpiceDBCluster created (operator deploys SpiceDB pods)
#
# IMPORTANT:
#   - prune: true - safe for application resources
#   - Secret template requires manual creation before SpiceDBCluster works
#   - See apps/spicedb/spicedb-secret.example.yaml for secret creation instructions
#
# Health Checks:
#   - Monitors SpiceDB deployment readiness
#   - Monitors PostgreSQL cluster status
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spicedb
  namespace: flux-system
spec:
  # Reference the flux-system GitRepository
  sourceRef:
    kind: GitRepository
    name: flux-system

  # Path to SpiceDB configuration in the repository
  path: ./apps/spicedb

  # Reconcile every 10 minutes (more frequent than infrastructure for apps)
  interval: 10m

  # Prune removed resources (safe for applications)
  prune: true

  # Wait for resources to be ready
  wait: true

  # Timeout for deployment
  timeout: 5m

  # Target namespace for generated resources
  targetNamespace: spicedb

  # Dependencies - ensure operator is deployed first
  dependsOn:
    # All infrastructure must be ready
    - name: infrastructure
    # SpiceDB operator must be deployed before SpiceDBCluster
    - name: spicedb-operator
      namespace: spicedb

  # Health checks for SpiceDB components
  healthChecks:
    # PostgreSQL cluster managed by CloudNativePG
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: spicedb-postgres
      namespace: spicedb
