apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-onepassword-connect
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  path: ./external-dns
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: bootstrap
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
