apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-waddle-server
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-cloudnative-pg
    - name: infra-external-dns
    - name: infra-onepassword-connect
    - name: infra-reloader
    - name: infra-spicedb-operator
    - name: infra-waddle-namespace
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: waddle-server
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgresql
      namespace: waddle
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgresql-spicedb
      namespace: waddle
    - apiVersion: authzed.com/v1alpha1
      kind: SpiceDBCluster
      name: spicedb
      namespace: waddle
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: waddle-server
      namespace: waddle
