apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-openebs.yaml
  - helmrepository-openebs.yaml
  - helmrelease-openebs.yaml
  - diskpool-mayastor.yaml
  - storageclass-openebs-mayastor.yaml
