apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-clickhouse
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-clickhouse-operator
    - name: openebs-postinstall
    - name: infra-external-secrets
    - name: infra-onepassword-connect
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  path: ./clickhouse
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: bootstrap
  healthChecks:
    - apiVersion: clickhouse.com/v1alpha1
      kind: ClickHouseCluster
      name: clickhouse
      namespace: clickhouse
