apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomization-openebs-core.yaml
  - kustomization-openebs-postinstall.yaml
  - kustomization-infra-external-secrets.yaml
  - kustomization-infra-onepassword-connect.yaml
  - kustomization-infra-cert-manager.yaml
  - kustomization-infra-external-dns.yaml
  - kustomization-infra-grafana-alloy.yaml
  - kustomization-infra-cloudnative-pg.yaml
  - kustomization-infra-waddle-namespace.yaml
  - kustomization-infra-spicedb-operator-source.yaml
  - kustomization-infra-spicedb-operator.yaml
  - kustomization-infra-cert-manager-issuer.yaml
  - kustomization-infra-cilium-gateway.yaml
  - livekit-redis-source.yaml
  - kustomization-infra-livekit-redis.yaml
  - livekit-sfu-source.yaml
  - kustomization-infra-livekit-sfu.yaml
  - livekit-egress-source.yaml
  - kustomization-infra-livekit-egress.yaml
  - waddle-server-source.yaml
  - kustomization-infra-teleport-core.yaml
  - kustomization-infra-teleport-postinstall.yaml
  - kustomization-infra-waddle-server.yaml
