apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: livekit-redis
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/waddle-social/waddle/gitops-livekit-redis
  ref:
    tag: latest
