apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: waddle-server
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/waddle-social/waddle/gitops-waddle-server
  ref:
    tag: latest
