package waddle:extension@0.1.0;

interface types {
    record detected-link {
        url: string,
        start-offset: u32,
        end-offset: u32,
    }

    record embed-element {
        element-name: string,
        namespace: string,
        attributes: list<tuple<string, string>>,
        children: list<string>,
    }

    record enrichment-result {
        embeds: list<embed-element>,
    }

    record feature-advertisement {
        namespace: string,
    }

    record extension-info {
        name: string,
        namespace: string,
        version: string,
        features: list<feature-advertisement>,
    }
}

interface enrich {
    use types.{detected-link, enrichment-result};
    enrich-message: func(body: string, links: list<detected-link>) -> enrichment-result;
}

interface lifecycle {
    use types.{extension-info};
    init: func(config: string) -> result<extension-info, string>;
}

world waddle-extension {
    import wasi:logging/logging@0.1.0-draft;
    import wasi:clocks/monotonic-clock@0.2.0;

    export lifecycle;
    export enrich;
}
