# ClusterSecretStore for 1Password
# =================================
#
# Provides cluster-wide access to secrets stored in 1Password.
# ExternalSecrets in any namespace can reference this store.
#
# Prerequisites:
# 1. 1Password Connect deployed (onepassword-connect.yaml)
# 2. Connect token secret created (onepassword-connect-token)
#
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      vaults:
        waddle-infra: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets
