# 1Password Connect Server Deployment
# ====================================
#
# Self-hosted 1Password Connect server for secret synchronization.
#
# PREREQUISITES:
# 1. Create 1Password Connect Server at https://my.1password.com
#    - Go to Developer Tools > Connect Server > New Server
#    - Save the 1password-credentials.json file
#    - Save the Connect Token
#
# 2. Create the credentials secret:
#    kubectl create secret generic onepassword-credentials \
#      --from-file=1password-credentials.json \
#      -n external-secrets
#
# 3. Create the token secret:
#    kubectl create secret generic onepassword-connect-token \
#      --from-literal=token=<your-connect-token> \
#      -n external-secrets
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: onepassword-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onepassword-connect
  template:
    metadata:
      labels:
        app.kubernetes.io/name: onepassword-connect
    spec:
      containers:
        - name: connect-api
          image: 1password/connect-api:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: onepassword-credentials
                  key: 1password-credentials.json
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: credentials
              mountPath: /home/opuser/.op/data
              readOnly: true
        - name: connect-sync
          image: 1password/connect-sync:latest
          env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: onepassword-credentials
                  key: 1password-credentials.json
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: credentials
              mountPath: /home/opuser/.op/data
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: onepassword-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: onepassword-connect
spec:
  selector:
    app.kubernetes.io/name: onepassword-connect
  ports:
    - port: 8080
      targetPort: 8080
      name: http
