use waddle_xmpp::XmppError;

use super::DatabasePubSubStorage;

const PUBSUB_SCHEMA_VERSION: i64 = 2;

impl DatabasePubSubStorage {
    pub(super) async fn initialize(&self) -> Result<(), XmppError> {
        self.execute(
            r#"
            CREATE TABLE IF NOT EXISTS pubsub_schema_version (
                version INTEGER NOT NULL PRIMARY KEY
            )
            "#,
            (),
        )
        .await?;

        let mut rows = self
            .query("SELECT version FROM pubsub_schema_version", ())
            .await?;
        let current: Option<i64> = match rows
            .next()
            .await
            .map_err(|error| XmppError::internal(error.to_string()))?
        {
            Some(row) => Some(
                row.get(0)
                    .map_err(|error| XmppError::internal(error.to_string()))?,
            ),
            None => None,
        };

        if current != Some(PUBSUB_SCHEMA_VERSION) {
            // Drop-and-recreate: CLAUDE.md greenlights breaking changes.
            for table in [
                "pubsub_items",
                "pubsub_subscriptions",
                "pubsub_affiliations",
                "pubsub_nodes",
            ] {
                self.execute(&format!("DROP TABLE IF EXISTS {table}"), ())
                    .await?;
            }
            self.execute("DELETE FROM pubsub_schema_version", ())
                .await?;
        }

        self.create_schema().await?;

        if current != Some(PUBSUB_SCHEMA_VERSION) {
            self.execute(
                "INSERT INTO pubsub_schema_version (version) VALUES (?)",
                crate::db_params![PUBSUB_SCHEMA_VERSION],
            )
            .await?;
        }
        Ok(())
    }

    async fn create_schema(&self) -> Result<(), XmppError> {
        // Bug 1 fix: use BIGINT for *_at_ms columns on Postgres (32-bit INTEGER
        // would overflow Unix-millis i64 timestamps ~1.7 trillion). Sqlite uses INTEGER.
        let nodes_ddl = match self.db.driver() {
            crate::db::DatabaseDriver::Sqlite => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_nodes (
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    access_model TEXT NOT NULL,
                    publish_model TEXT NOT NULL,
                    max_items INTEGER NOT NULL,
                    persist_items INTEGER NOT NULL,
                    deliver_payloads INTEGER NOT NULL,
                    notify_retract INTEGER NOT NULL,
                    notify_delete INTEGER NOT NULL,
                    send_last_published_item TEXT NOT NULL,
                    created_at_ms INTEGER NOT NULL,
                    PRIMARY KEY (owner_jid, node_name)
                )
                "#
            }
            crate::db::DatabaseDriver::Postgres => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_nodes (
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    access_model TEXT NOT NULL,
                    publish_model TEXT NOT NULL,
                    max_items BIGINT NOT NULL,
                    persist_items INTEGER NOT NULL,
                    deliver_payloads INTEGER NOT NULL,
                    notify_retract INTEGER NOT NULL,
                    notify_delete INTEGER NOT NULL,
                    send_last_published_item TEXT NOT NULL,
                    created_at_ms BIGINT NOT NULL,
                    PRIMARY KEY (owner_jid, node_name)
                )
                "#
            }
        };
        self.execute(nodes_ddl, ()).await?;

        let items_ddl = match self.db.driver() {
            crate::db::DatabaseDriver::Sqlite => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_items (
                    seq INTEGER PRIMARY KEY AUTOINCREMENT,
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    item_id TEXT NOT NULL,
                    payload_xml TEXT,
                    publisher_jid TEXT,
                    published_at_ms INTEGER NOT NULL,
                    UNIQUE (owner_jid, node_name, item_id),
                    FOREIGN KEY (owner_jid, node_name)
                        REFERENCES pubsub_nodes(owner_jid, node_name)
                        ON DELETE CASCADE
                )
                "#
            }
            crate::db::DatabaseDriver::Postgres => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_items (
                    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    item_id TEXT NOT NULL,
                    payload_xml TEXT,
                    publisher_jid TEXT,
                    published_at_ms BIGINT NOT NULL,
                    UNIQUE (owner_jid, node_name, item_id),
                    FOREIGN KEY (owner_jid, node_name)
                        REFERENCES pubsub_nodes(owner_jid, node_name)
                        ON DELETE CASCADE
                )
                "#
            }
        };
        self.execute(items_ddl, ()).await?;

        self.execute(
            "CREATE INDEX IF NOT EXISTS idx_pubsub_items_node_seq ON pubsub_items (owner_jid, node_name, seq DESC)",
            (),
        )
        .await?;
        self.execute(
            "CREATE INDEX IF NOT EXISTS idx_pubsub_items_owner_item ON pubsub_items (owner_jid, item_id)",
            (),
        )
        .await?;

        let subs_ddl = match self.db.driver() {
            crate::db::DatabaseDriver::Sqlite => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_subscriptions (
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    subid TEXT NOT NULL,
                    subscriber_jid TEXT NOT NULL,
                    state TEXT NOT NULL,
                    created_at_ms INTEGER NOT NULL,
                    PRIMARY KEY (owner_jid, node_name, subid),
                    FOREIGN KEY (owner_jid, node_name)
                        REFERENCES pubsub_nodes(owner_jid, node_name)
                        ON DELETE CASCADE
                )
                "#
            }
            crate::db::DatabaseDriver::Postgres => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_subscriptions (
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    subid TEXT NOT NULL,
                    subscriber_jid TEXT NOT NULL,
                    state TEXT NOT NULL,
                    created_at_ms BIGINT NOT NULL,
                    PRIMARY KEY (owner_jid, node_name, subid),
                    FOREIGN KEY (owner_jid, node_name)
                        REFERENCES pubsub_nodes(owner_jid, node_name)
                        ON DELETE CASCADE
                )
                "#
            }
        };
        self.execute(subs_ddl, ()).await?;
        self.execute(
            "CREATE INDEX IF NOT EXISTS idx_pubsub_subs_subscriber ON pubsub_subscriptions (owner_jid, subscriber_jid)",
            (),
        )
        .await?;

        let affs_ddl = match self.db.driver() {
            crate::db::DatabaseDriver::Sqlite => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_affiliations (
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    entity_jid TEXT NOT NULL,
                    affiliation TEXT NOT NULL,
                    updated_at_ms INTEGER NOT NULL,
                    PRIMARY KEY (owner_jid, node_name, entity_jid),
                    FOREIGN KEY (owner_jid, node_name)
                        REFERENCES pubsub_nodes(owner_jid, node_name)
                        ON DELETE CASCADE
                )
                "#
            }
            crate::db::DatabaseDriver::Postgres => {
                r#"
                CREATE TABLE IF NOT EXISTS pubsub_affiliations (
                    owner_jid TEXT NOT NULL,
                    node_name TEXT NOT NULL,
                    entity_jid TEXT NOT NULL,
                    affiliation TEXT NOT NULL,
                    updated_at_ms BIGINT NOT NULL,
                    PRIMARY KEY (owner_jid, node_name, entity_jid),
                    FOREIGN KEY (owner_jid, node_name)
                        REFERENCES pubsub_nodes(owner_jid, node_name)
                        ON DELETE CASCADE
                )
                "#
            }
        };
        self.execute(affs_ddl, ()).await?;
        self.execute(
            "CREATE INDEX IF NOT EXISTS idx_pubsub_affs_entity ON pubsub_affiliations (owner_jid, entity_jid)",
            (),
        )
        .await?;

        Ok(())
    }
}
