# cert-manager HelmRelease
# ========================
#
# Deploys cert-manager via Helm using values from infrastructure-k8s/cert-manager/.
# Provides automated TLS certificate management using Let's Encrypt ACME with
# Cloudflare DNS01 challenge solver.
#
# Chart: jetstack/cert-manager
# Version: v1.16.2
# Namespace: cert-manager
#
# Features enabled:
#   - CRD installation via Helm
#   - Webhook for resource validation
#   - Cainjector for CA bundle injection
#   - DNS01 recursive nameservers for Cloudflare
#   - Prometheus metrics
#
# PREREQUISITE: The Kubernetes Secret 'cloudflare-api-token' must exist
# in the 'cert-manager' namespace before this HelmRelease is applied.
# The secret is NOT managed by Flux (security best practice).
#
# Create the secret manually:
#   kubectl create namespace cert-manager
#   kubectl create secret generic cloudflare-api-token \
#     --from-literal=api-token=<your-cloudflare-api-token> \
#     -n cert-manager
#
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  # Reference the cert-manager Helm repository
  chart:
    spec:
      chart: cert-manager
      version: "v1.16.2"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system

  # Reconcile Helm release hourly (stable component)
  interval: 1h

  # Use Helm values from the ConfigMap generated by kustomization.yaml
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
      valuesKey: values.yaml

  # Install configuration
  install:
    # Create namespace if it doesn't exist
    createNamespace: true

    # Install CRDs via Helm
    crds: CreateReplace

    # Remediation on install failure
    remediation:
      retries: 3

  # Upgrade configuration
  upgrade:
    # Clean up old resources on upgrade
    cleanupOnFail: true

    # Upgrade CRDs
    crds: CreateReplace

    # Remediation on upgrade failure
    remediation:
      retries: 3
      # Rollback on upgrade failure
      remediateLastFailure: true

  # Rollback configuration
  rollback:
    # Keep rollback history
    cleanupOnFail: true

  # Wait for all resources to be ready
  timeout: 10m

  # Dependencies
  dependsOn:
    # Cilium must be ready for networking
    - name: cilium
      namespace: kube-system

  # Values override (can be used for quick patches without editing ConfigMap)
  # values: {}
