# cert-manager ClusterIssuers Kustomization
# ==========================================
#
# Deploys ClusterIssuers for Let's Encrypt ACME certificate issuance.
# This is separate from the main cert-manager deployment to ensure
# proper dependency ordering - ClusterIssuers can only be created
# after cert-manager CRDs are installed.
#
# ClusterIssuers deployed:
#   - letsencrypt-staging: For testing (not browser-trusted)
#   - letsencrypt-production: For production (browser-trusted)
#
# IMPORTANT: Update the email address in the ClusterIssuer files before
# deploying. The email is used for Let's Encrypt notifications.
#
# PREREQUISITE: The Cloudflare API token Secret must exist before
# ClusterIssuers can successfully issue certificates:
#
#   kubectl create secret generic cloudflare-api-token \
#     --from-literal=api-token=<your-cloudflare-api-token> \
#     -n cert-manager
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-clusterissuers
  namespace: flux-system
spec:
  # Reference the flux-system GitRepository
  sourceRef:
    kind: GitRepository
    name: flux-system

  # Path to ClusterIssuers kustomization in the repository
  path: ./infrastructure-k8s/cert-manager/clusterissuers

  # Reconcile hourly
  interval: 1h

  # Allow pruning ClusterIssuers (safe - they don't hold certificates)
  prune: true

  # Wait for resources to be ready
  wait: true

  # Timeout for ClusterIssuer creation
  timeout: 5m

  # Dependencies - cert-manager HelmRelease must be ready first
  dependsOn:
    # cert-manager must be fully deployed before creating ClusterIssuers
    - name: cert-manager

  # Target namespace (ClusterIssuers are cluster-scoped but reference
  # secrets in cert-manager namespace)
  targetNamespace: cert-manager

  # Only include ClusterIssuer resources from the path
  # This filters out Helm values, verification manifests, etc.
  patches:
    - patch: |
        - op: add
          path: /metadata/labels/flux.kustomize.toolkit.fluxcd.io~1component
          value: clusterissuer
      target:
        kind: ClusterIssuer

  # Health checks for ClusterIssuers
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-staging
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-production
