# Cilium CNI Kustomization
# ========================
#
# Applies the Cilium configuration from infrastructure-k8s/cilium/.
# This Kustomization generates the ConfigMap with Helm values
# that the HelmRelease references.
#
# Note: The actual Cilium deployment is handled by the HelmRelease.
# This Kustomization ensures the values ConfigMap is created and
# any additional resources (verification manifests, etc.) are applied.
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  # Reference the flux-system GitRepository
  sourceRef:
    kind: GitRepository
    name: flux-system

  # Path to Cilium configuration in the repository
  path: ./infrastructure-k8s/cilium

  # Reconcile hourly (CNI is stable, infrequent changes)
  interval: 1h

  # IMPORTANT: Do NOT prune CNI resources - could break cluster networking
  prune: false

  # Wait for resources to be ready
  wait: true

  # Timeout for CNI deployment (can take time on initial setup)
  timeout: 10m

  # Dependencies
  dependsOn:
    # Gateway API CRDs must be installed before Cilium
    - name: gateway-api-crds

  # Target namespace for generated resources
  targetNamespace: kube-system

  # Health checks for Cilium components
  healthChecks:
    # Cilium agent DaemonSet
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cilium
      namespace: kube-system
    # Cilium operator Deployment
    - apiVersion: apps/v1
      kind: Deployment
      name: cilium-operator
      namespace: kube-system
