# CloudNativePG Kustomization
# ===========================
#
# Applies the CloudNativePG configuration from infrastructure-k8s/cnpg/.
# This Kustomization generates the ConfigMap with Helm values
# that the HelmRelease references.
#
# Note: The actual operator deployment is handled by the HelmRelease.
# This Kustomization ensures the values ConfigMap is created.
#
# PostgreSQL clusters are created separately in application namespaces
# using Cluster custom resources after the operator is ready.
#
# IMPORTANT:
# - prune: false - prevents accidental deletion of database operator
# - This is critical for data safety as operator manages PostgreSQL clusters
#
# Dependencies:
# - Cilium CNI (Phase 6) - networking
# - Proxmox CSI (Phase 7) - storage for PostgreSQL volumes
#
# See infrastructure-k8s/cnpg/README.md for:
# - PostgreSQL cluster configuration examples
# - Backup and recovery setup
# - Monitoring integration
# - Troubleshooting guide
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  # Reference the flux-system GitRepository
  sourceRef:
    kind: GitRepository
    name: flux-system

  # Path to CloudNativePG configuration in the repository
  path: ./infrastructure-k8s/cnpg

  # Reconcile hourly (operator is stable)
  interval: 1h

  # IMPORTANT: Do NOT prune database operator resources
  # Pruning could cause data loss or cluster management issues
  prune: false

  # Wait for resources to be ready
  wait: true

  # Timeout for deployment
  timeout: 10m

  # Dependencies - ensure networking and storage are ready
  dependsOn:
    # Cilium must be ready for networking
    - name: cilium
    # Proxmox CSI must be ready for PostgreSQL storage
    - name: proxmox-csi

  # Target namespace for generated ConfigMap
  targetNamespace: cnpg-system

  # Health checks for operator components
  healthChecks:
    # CloudNativePG operator Deployment
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudnative-pg
      namespace: cnpg-system
