# CloudNativePG Helm Repository
# =============================
#
# Defines the Helm repository source for CloudNativePG operator chart.
# Referenced by the cloudnative-pg HelmRelease.
#
# Chart repository: https://github.com/cloudnative-pg/charts
# Documentation: https://cloudnative-pg.io/
#
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  # Official CloudNativePG Helm chart repository
  url: https://cloudnative-pg.github.io/charts

  # Check for chart updates hourly
  interval: 1h

  # Timeout for fetching repository index
  timeout: 1m
