# CloudNativePG HelmRelease
# =========================
#
# Deploys CloudNativePG operator via Helm using values from infrastructure-k8s/cnpg/.
# Provides automated PostgreSQL cluster management including high availability,
# backup/recovery, and monitoring integration.
#
# Chart: cnpg/cloudnative-pg
# Version: 0.22.1 (Operator version 1.25.0)
# Namespace: cnpg-system
#
# Features enabled:
#   - CRD installation via Helm
#   - Webhook for resource validation
#   - Prometheus metrics (port 9187)
#   - Priority class: system-cluster-critical
#
# PostgreSQL Clusters:
#   After operator deployment, create Cluster resources in application namespaces.
#   Clusters will use Proxmox CSI storage (Phase 7) for persistent volumes.
#
# Dependencies:
#   - Cilium CNI (Phase 6) - networking for PostgreSQL pods
#   - Proxmox CSI (Phase 7) - storage for PostgreSQL volumes
#
# IMPORTANT: This HelmRelease only deploys the operator. PostgreSQL clusters
# are created separately using Cluster custom resources.
#
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  # Reference the CloudNativePG Helm repository
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.22.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system

  # Reconcile Helm release hourly (stable component)
  interval: 1h

  # Use Helm values from the ConfigMap generated by kustomization.yaml
  valuesFrom:
    - kind: ConfigMap
      name: cnpg-values
      valuesKey: values.yaml

  # Install configuration
  install:
    # Create namespace if it doesn't exist
    createNamespace: true

    # Install CRDs via Helm (CreateReplace to update existing)
    crds: CreateReplace

    # Remediation on install failure
    remediation:
      retries: 3

  # Upgrade configuration
  upgrade:
    # Clean up old resources on upgrade
    cleanupOnFail: true

    # Upgrade CRDs
    crds: CreateReplace

    # Remediation on upgrade failure
    remediation:
      retries: 3
      # Rollback on upgrade failure
      remediateLastFailure: true

  # Rollback configuration
  rollback:
    # Keep rollback history
    cleanupOnFail: true

  # Wait for all resources to be ready
  timeout: 10m

  # Dependencies - ensure networking and storage are ready
  dependsOn:
    # Cilium must be ready for networking
    - name: cilium
      namespace: kube-system
    # Proxmox CSI must be ready for storage
    - name: proxmox-csi
      namespace: csi-proxmox

  # Values override (can be used for quick patches without editing ConfigMap)
  # values: {}
