# Gateway API Kustomization
# =========================
#
# Deploys Gateway API ingress resources from infrastructure-k8s/gateway/.
# Provides HTTP/HTTPS ingress with TLS termination via cert-manager.
#
# Prerequisites:
# - Cilium CNI with Gateway API enabled (provides GatewayClass 'cilium')
# - cert-manager with ClusterIssuers (provides certificate automation)
# - Cloudflare DNS A record pointing to LoadBalancer IP
#
# IMPORTANT:
# - Update infrastructure-k8s/gateway/gateway.yaml with your domain
# - Update infrastructure-k8s/gateway/certificate.yaml with your domain
# - Configure DNS after Gateway is deployed and LoadBalancer IP is assigned
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  # Reference the flux-system GitRepository
  sourceRef:
    kind: GitRepository
    name: flux-system

  # Path to Gateway configuration in the repository
  path: ./infrastructure-k8s/gateway

  # Reconcile hourly (Gateway is stable, infrequent changes)
  interval: 1h

  # IMPORTANT: Do NOT prune Gateway resources - could break ingress
  # Gateway deletion would disrupt all external traffic
  prune: false

  # Wait for resources to be ready
  wait: true

  # Timeout for Gateway deployment
  timeout: 5m

  # Dependencies - ensure prerequisites exist
  dependsOn:
    # cert-manager provides ClusterIssuers for TLS certificates
    - name: cert-manager-clusterissuers
    # Cilium provides GatewayClass 'cilium'
    - name: cilium

  # Target namespace for generated resources
  # Note: Gateway creates its own namespace (gateway-ingress)
  # This targetNamespace is for any non-namespaced resources
  targetNamespace: gateway-ingress

  # Health checks for Gateway readiness
  healthChecks:
    # Gateway resource health
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: gateway
      namespace: gateway-ingress
