# =============================================================================
# FLUX KUSTOMIZATION: NETWORK POLICIES
# =============================================================================
#
# Phase 14: Network Segmentation with Zero-Trust Networking
#
# Deploys NetworkPolicy resources from infrastructure-k8s/network-policies/
#
# Dependencies:
# - Cilium CNI must be operational (enforces NetworkPolicies)
#
# Configuration:
# - interval: 1h (stable policies, infrequent changes)
# - prune: false (protect critical security policies from accidental deletion)
#
# =============================================================================
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-policies
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure-k8s/network-policies
  prune: false  # Critical security policies - prevent accidental deletion
  timeout: 5m

  # Requires Cilium CNI for NetworkPolicy enforcement
  dependsOn:
    - name: cilium

  healthChecks:
    # Verify key policies are deployed
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: default-deny-all
      namespace: observability
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: default-deny-all
      namespace: spicedb
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: allow-dns
      namespace: observability
