# Flux HelmRelease for Tempo
# Distributed tracing with TraceQL query support
# Deploys after Proxmox CSI for storage provisioning
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  chart:
    spec:
      chart: tempo
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
      valuesKey: values.yaml
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  timeout: 10m
  dependsOn:
    - name: proxmox-csi
      namespace: csi-proxmox
