# Flux HelmRelease for Grafana
# Visualization and dashboards for logs, metrics, and traces
# Deploys after data sources (Loki/Tempo/Mimir) are ready
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  chart:
    spec:
      chart: grafana
      version: "8.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
      valuesKey: values.yaml
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  timeout: 10m
  dependsOn:
    - name: loki
      namespace: observability
    - name: tempo
      namespace: observability
    - name: mimir
      namespace: observability
