# Proxmox CSI HelmRelease
# =======================
#
# Deploys Proxmox CSI driver via Helm using values from infrastructure-k8s/storage/.
# Migrates the manually-installed CSI driver (Phase 7) to Flux management.
#
# Chart: proxmox-csi/proxmox-csi-plugin
# Version: 0.13.0
# Namespace: csi-proxmox
#
# PREREQUISITE: The Kubernetes Secret 'proxmox-csi-credentials' must exist
# in the 'csi-proxmox' namespace before this HelmRelease is applied.
# The secret is NOT managed by Flux (security best practice).
#
# Create the secret manually:
#   kubectl create namespace csi-proxmox
#   kubectl create secret generic proxmox-csi-credentials \
#     --from-file=config.yaml=proxmox-csi-config.yaml \
#     -n csi-proxmox
#
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  # Reference the Proxmox CSI Helm repository
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: "0.13.0"
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi
        namespace: flux-system

  # Reconcile Helm release hourly (stable component)
  interval: 1h

  # Use Helm values from the ConfigMap generated by kustomization.yaml
  valuesFrom:
    - kind: ConfigMap
      name: proxmox-csi-values
      valuesKey: values.yaml

  # Install configuration
  install:
    # Create namespace if it doesn't exist
    createNamespace: true

    # Remediation on install failure
    remediation:
      retries: 3

  # Upgrade configuration
  upgrade:
    # Clean up old resources on upgrade
    cleanupOnFail: true

    # Remediation on upgrade failure
    remediation:
      retries: 3
      # Rollback on upgrade failure
      remediateLastFailure: true

  # Rollback configuration
  rollback:
    # Keep rollback history
    cleanupOnFail: true

  # Wait for all resources to be ready
  timeout: 10m

  # Dependencies
  dependsOn:
    # Cilium must be ready for networking
    - name: cilium
      namespace: kube-system

  # Values override (can be used for quick patches without editing ConfigMap)
  # values: {}
