# Proxmox CSI Kustomization
# =========================
#
# Applies the Proxmox CSI configuration from infrastructure-k8s/storage/.
# This Kustomization generates the ConfigMap with Helm values
# that the HelmRelease references.
#
# Note: The actual CSI deployment is handled by the HelmRelease.
# This Kustomization ensures the values ConfigMap is created and
# any additional resources (StorageClass, verification manifests) are applied.
#
# SECURITY NOTE:
# The Kubernetes Secret 'proxmox-csi-credentials' is NOT managed by this
# Kustomization. It must be created manually before deploying the CSI driver.
# See infrastructure-k8s/storage/README.md for instructions.
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox-csi
  namespace: flux-system
spec:
  # Reference the flux-system GitRepository
  sourceRef:
    kind: GitRepository
    name: flux-system

  # Path to storage configuration in the repository
  path: ./infrastructure-k8s/storage

  # Reconcile hourly (storage driver is stable)
  interval: 1h

  # IMPORTANT: Do NOT prune storage driver resources
  # Pruning could cause data loss or pod failures
  prune: false

  # Wait for resources to be ready
  wait: true

  # Timeout for CSI deployment
  timeout: 10m

  # Dependencies
  dependsOn:
    # Cilium must be ready for networking
    - name: cilium

  # Target namespace for generated resources
  targetNamespace: csi-proxmox

  # Health checks for CSI components
  healthChecks:
    # CSI controller Deployment
    - apiVersion: apps/v1
      kind: Deployment
      name: proxmox-csi-plugin-controller
      namespace: csi-proxmox
    # CSI node DaemonSet
    - apiVersion: apps/v1
      kind: DaemonSet
      name: proxmox-csi-plugin-node
      namespace: csi-proxmox
