package cuenv

import "github.com/cuenv/cuenv/schema/rules"

rules.#DirectoryRules

ignore: git: [
	"# Astro",
	".astro/",
	"",
	"# Bun",
	"node_modules",
	"",
	"# Claude",
	".claude/",
	"",
	"# Claude worktrees",
	".worktrees/",
	".codex",
	"",
	"# Cuenv",
	".cuenv",
	"",
	"# Cloudflare",
	".wrangler/",
	"",
	"# Editor state",
	".vscode/",
	"",
	"# direnv",
	".direnv",
	"",
	"# Nix",
	"result",
	"",
	"# Rust",
	"/target/",
	"",
	"dist/",
	"build/",
	"coverage/",
	".turbo/",
	"bun.lockb",
	".env",
	".env.*",
	"*.log",
	".DS_Store",
	"",
	"# Moonrepo cache",
	".moon/",
	"",
	"# CUE generated",
	"cue.mod/pkg/",
	"",
	"# TLS certificates (generated locally, never committed)",
	"server/certs/",
	"",
	"# Gateway generated schemas",
	"gateway/schemas/",
	"gateway/supergraph.graphql",
	"",
	"# Android (apps/android)",
	"apps/android/.gradle/",
	"apps/android/.kotlin/",
	"apps/android/local.properties",
	"apps/android/core/client/src/main/jniLibs/",
	"apps/android/keystore.properties",
	"*.jks",
]
