apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rustfs-values
  namespace: rustfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rustfs-values
    creationPolicy: Owner
    template:
      data:
        values.yaml: |
          secret:
            rustfs:
              access_key: "{{ .accessKey }}"
              secret_key: "{{ .secretKey }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: rustfs-credentials
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: rustfs-credentials
        property: secretKey
