apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
  namespace: rustfs
spec:
  interval: 30m
  chart:
    spec:
      chart: rustfs
      version: 0.0.91
      sourceRef:
        kind: HelmRepository
        name: rustfs
        namespace: rustfs
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: rustfs-values
      valuesKey: values.yaml
  values:
    replicaCount: 1
    mode:
      standalone:
        enabled: true
      distributed:
        enabled: false
    storageclass:
      name: openebs-mayastor
    dataStorageSize: 50Gi
    logStorageSize: 10Gi
