//! XEP-0060 subscription typed payloads.

use std::{fmt, str::FromStr};

use jid::Jid;
use serde::{Deserialize, Serialize};

/// Opaque subscription identifier (XEP-0060 §6.1.6).
///
/// Generated by the service. Treated as opaque on the wire; internally a UUID.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SubId(String);

impl SubId {
    /// Generate a fresh subid backed by a v4 UUID.
    pub fn generate() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }

    /// Wrap an existing identifier (used by storage when reading rows back).
    pub fn from_raw(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for SubId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// XEP-0060 §4.2 subscription states.
///
/// `None` is the absence of a subscription and is never persisted; it is
/// exposed only so handlers can return it from `<subscription/>` queries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SubscriptionState {
    None,
    Pending,
    Unconfigured,
    Subscribed,
}

impl fmt::Display for SubscriptionState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            SubscriptionState::None => "none",
            SubscriptionState::Pending => "pending",
            SubscriptionState::Unconfigured => "unconfigured",
            SubscriptionState::Subscribed => "subscribed",
        };
        f.write_str(s)
    }
}

impl FromStr for SubscriptionState {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "none" => Ok(SubscriptionState::None),
            "pending" => Ok(SubscriptionState::Pending),
            "unconfigured" => Ok(SubscriptionState::Unconfigured),
            "subscribed" => Ok(SubscriptionState::Subscribed),
            _ => Err(()),
        }
    }
}

/// A persisted subscription (XEP-0060 §6).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Subscription {
    pub subid: SubId,
    pub subscriber: Jid,
    pub state: SubscriptionState,
    pub created_at_ms: i64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn subid_generates_unique() {
        let a = SubId::generate();
        let b = SubId::generate();
        assert_ne!(a, b);
        assert_eq!(a.as_str().len(), 36); // UUID v4 length
    }

    #[test]
    fn subscription_state_round_trips() {
        for state in [
            SubscriptionState::None,
            SubscriptionState::Pending,
            SubscriptionState::Unconfigured,
            SubscriptionState::Subscribed,
        ] {
            let s = state.to_string();
            assert_eq!(s.parse::<SubscriptionState>().unwrap(), state);
        }
    }

    #[test]
    fn subscription_state_unknown_is_err() {
        assert!("garbage".parse::<SubscriptionState>().is_err());
    }
}
