# ServiceMonitor for cert-manager metrics
# Scrapes cert-manager controller metrics from port 9402
# Reference: infrastructure-k8s/cert-manager/helm-values.yaml (prometheus.servicemonitor.enabled)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - cert-manager
  endpoints:
    - port: tcp-prometheus-servicemonitor
      interval: 30s
      path: /metrics
      honorLabels: true
