# ServiceMonitor for Cilium metrics
# Scrapes Cilium agent metrics from port 9962
# Reference: infrastructure-k8s/cilium/helm-values.yaml (prometheus.enabled: true)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: prometheus
      interval: 30s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
