# PodMonitor for CloudNativePG operator metrics
# Scrapes CloudNativePG operator metrics
# Reference: infrastructure-k8s/cnpg/helm-values.yaml
#
# Note: PostgreSQL cluster metrics are scraped via enablePodMonitor: true
# in Cluster resources (apps/spicedb/postgres-cluster.yaml)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  namespaceSelector:
    matchNames:
      - cnpg-system
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
