# Test Pod for Loki log ingestion verification
#
# Usage:
#   kubectl apply -f test-logging.yaml
#   # Wait for logs to be collected
#   sleep 30
#   # Query in Grafana Explore (Loki data source):
#   #   {namespace="observability", app="log-generator"}
#   # Cleanup:
#   kubectl delete -f test-logging.yaml
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  namespace: observability
  labels:
    app: log-generator
    app.kubernetes.io/name: log-generator
    app.kubernetes.io/part-of: observability
spec:
  containers:
    - name: logger
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "[INFO] Starting log generator"
          i=0
          while true; do
            i=$((i+1))
            echo "[INFO] Test log message #$i at $(date -Iseconds)"
            echo "[WARN] Test warning message #$i at $(date -Iseconds)"
            if [ $((i % 5)) -eq 0 ]; then
              echo "[ERROR] Test error message #$i at $(date -Iseconds)" >&2
            fi
            sleep 5
          done
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
