apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-waddle-social-tls
  namespace: default
spec:
  secretName: api-waddle-social-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - api.waddle.social
