apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waddle-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.apps.waddle.chat"
      tls:
        mode: Terminate
        certificateRefs:
          - name: apps-wildcard-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.apps.waddle.chat"
      allowedRoutes:
        namespaces:
          from: All
    - name: https-xmpp
      protocol: HTTPS
      port: 443
      hostname: xmpp.waddle.social
      tls:
        mode: Terminate
        certificateRefs:
          - name: xmpp-waddle-social-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: http-xmpp
      protocol: HTTP
      port: 80
      hostname: xmpp.waddle.social
      allowedRoutes:
        namespaces:
          from: All
    - name: https-sfu
      protocol: HTTPS
      port: 443
      hostname: sfu.waddle.social
      tls:
        mode: Terminate
        certificateRefs:
          - name: sfu-waddle-social-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: http-sfu
      protocol: HTTP
      port: 80
      hostname: sfu.waddle.social
      allowedRoutes:
        namespaces:
          from: All
    - name: turn-passthrough
      protocol: TLS
      port: 443
      hostname: turn.waddle.social
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
    - name: teleport-passthrough
      protocol: TLS
      port: 443
      hostname: "teleport.waddle.social"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
    - name: teleport-grpc-passthrough
      protocol: TLS
      port: 443
      hostname: "*.teleport.cluster.local"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
    - name: teleport-kube-passthrough
      protocol: TLS
      port: 443
      hostname: "*.teleport.waddle.social"
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
