# CSI Test Namespace
# ==================
#
# This manifest creates the 'csi-test' namespace for CSI verification tests.
# Apply this namespace BEFORE applying any test manifests.
#
# Usage:
#   kubectl apply -f verification/namespace.yaml
#   kubectl apply -f verification/test-pvc.yaml
#   # or
#   kubectl apply -f verification/test-statefulset.yaml
#
# Cleanup:
#   kubectl delete namespace csi-test
#
# =============================================================================

---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-test
  labels:
    app.kubernetes.io/name: csi-test
    app.kubernetes.io/purpose: verification
