# Proxmox CSI PVC Provisioning Test
# ==================================
#
# This manifest tests PersistentVolumeClaim provisioning with the Proxmox CSI driver.
#
# PREREQUISITE:
#   Apply the namespace manifest first:
#     kubectl apply -f verification/namespace.yaml
#
# Usage:
#   1. Apply namespace (if not already created):
#      kubectl apply -f verification/namespace.yaml
#
#   2. Apply this manifest:
#      kubectl apply -f verification/test-pvc.yaml
#
#   3. Check PVC status (should transition to Bound):
#      kubectl get pvc -n csi-test
#
#   4. Check PV created:
#      kubectl get pv
#
#   5. Check test pod status:
#      kubectl get pod -n csi-test
#
#   6. Wait for pod to be ready:
#      kubectl wait --for=condition=Ready pod/test-pod -n csi-test --timeout=120s
#
#   7. Verify data written to volume:
#      kubectl exec -n csi-test test-pod -- cat /data/test.txt
#
#   8. Verify volume in Proxmox UI:
#      - Open Proxmox web interface
#      - Navigate to the VM running the test pod
#      - Check Hardware → Hard Disk for new disk attachment
#
#   9. Cleanup:
#      kubectl delete -f verification/test-pvc.yaml
#
# Expected Results:
#   - PVC status: Bound
#   - PV created with Proxmox volume ID
#   - Pod status: Running
#   - Output: "CSI test successful"
#   - Disk visible in Proxmox VM hardware
#
# Troubleshooting:
#   - PVC stuck in Pending:
#     kubectl describe pvc test-pvc -n csi-test
#     kubectl logs -n csi-proxmox -l app.kubernetes.io/component=controller
#
#   - Pod stuck in ContainerCreating:
#     kubectl describe pod test-pod -n csi-test
#     kubectl logs -n csi-proxmox -l app.kubernetes.io/component=node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: csi-test
  labels:
    app: csi-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      # Small test volume (1GB)
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: csi-test
  labels:
    app: csi-test
spec:
  containers:
    - name: test
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "CSI test successful" > /data/test.txt
          echo "Volume mounted at /data"
          echo "Content written:"
          cat /data/test.txt
          echo "Disk usage:"
          df -h /data
          echo "Sleeping to keep pod running..."
          sleep 3600
      volumeMounts:
        - name: test-volume
          mountPath: /data
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc
  restartPolicy: Never
