# Proxmox CSI StatefulSet Volume Test
# ====================================
#
# This manifest tests StatefulSet volume provisioning with volumeClaimTemplates.
# StatefulSets are commonly used for databases (PostgreSQL, MySQL, etc.)
# where each replica needs its own persistent volume.
#
# PREREQUISITE:
#   Apply the namespace manifest first:
#     kubectl apply -f verification/namespace.yaml
#
# Usage:
#   1. Apply namespace (if not already created):
#      kubectl apply -f verification/namespace.yaml
#
#   2. Apply this manifest:
#      kubectl apply -f verification/test-statefulset.yaml
#
#   3. Check PVCs created (one per replica):
#      kubectl get pvc -n csi-test
#      # Expected: data-test-statefulset-0, data-test-statefulset-1
#
#   4. Check StatefulSet status:
#      kubectl get statefulset -n csi-test
#
#   5. Check pods:
#      kubectl get pods -n csi-test -l app=test-statefulset
#
#   6. Wait for pods to be ready:
#      kubectl wait --for=condition=Ready pod -l app=test-statefulset -n csi-test --timeout=180s
#
#   7. Verify each pod wrote its hostname:
#      kubectl exec -n csi-test test-statefulset-0 -- cat /data/hostname.txt
#      kubectl exec -n csi-test test-statefulset-1 -- cat /data/hostname.txt
#
#   8. Test data persistence (delete and recreate pod):
#      kubectl delete pod test-statefulset-0 -n csi-test
#      kubectl wait --for=condition=Ready pod/test-statefulset-0 -n csi-test --timeout=120s
#      kubectl exec -n csi-test test-statefulset-0 -- cat /data/hostname.txt
#      # Should still show "test-statefulset-0"
#
#   9. Cleanup:
#      kubectl delete -f verification/test-statefulset.yaml
#      # NOTE: PVCs are NOT automatically deleted with StatefulSet
#      # Delete manually if needed:
#      kubectl delete pvc -n csi-test -l app=test-statefulset
#
# Expected Results:
#   - 2 PVCs created (data-test-statefulset-0, data-test-statefulset-1)
#   - 2 PVs created and bound
#   - Both pods running
#   - Each pod has its own volume with unique data
#   - Data persists across pod restarts
#
# Use Case:
#   This pattern is used by CloudNativePG (Phase 10) for PostgreSQL,
#   Redis clusters, Kafka brokers, and other stateful applications.

---
apiVersion: v1
kind: Service
metadata:
  name: test-statefulset
  namespace: csi-test
  labels:
    app: test-statefulset
spec:
  # Headless service for StatefulSet DNS
  clusterIP: None
  selector:
    app: test-statefulset
  ports:
    - port: 80
      name: http

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset
  namespace: csi-test
  labels:
    app: test-statefulset
spec:
  serviceName: test-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: test-statefulset
  template:
    metadata:
      labels:
        app: test-statefulset
    spec:
      containers:
        - name: test
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "StatefulSet pod: $(hostname)"
              echo "Writing hostname to persistent volume..."
              echo $(hostname) > /data/hostname.txt
              echo "Content of /data/hostname.txt:"
              cat /data/hostname.txt
              echo "Disk usage:"
              df -h /data
              echo "Sleeping to keep pod running..."
              sleep 3600
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
      terminationGracePeriodSeconds: 10
  # Volume claim templates - each pod gets its own PVC
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: test-statefulset
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: proxmox-csi
        resources:
          requests:
            # Small test volume (1GB)
            storage: 1Gi
