import type {
  WasmAuthenticationCondition,
  WasmControlErrorPayload,
  WasmDriverErrorReason,
  WasmStreamErrorCondition,
} from "./wasm-types";

export const WASM_DRIVER_ERROR_DETAILS: Record<WasmDriverErrorReason, string> = {
  "core-error": "XMPP core error",
  "invalid-transport-scheme": "Invalid WebSocket transport scheme",
  "missing-websocket-host": "WebSocket endpoint has no host",
  "empty-resource": "XMPP resource is empty",
  "empty-stanza-id": "XMPP stanza id is empty",
  "request-id-exhausted": "XMPP request ids are exhausted",
  "duplicate-request": "Duplicate XMPP request",
  "duplicate-stanza-correlation": "Duplicate XMPP stanza correlation",
  "unknown-request": "Unknown XMPP request",
  "unknown-stanza-correlation": "Unknown XMPP stanza correlation",
  "invalid-phase-transition": "Invalid XMPP session phase transition",
  "invalid-state-transition": "Invalid XMPP client state transition",
  "missing-stream-feature": "Required XMPP stream feature is missing",
  "invalid-stream-features": "Invalid XMPP stream features",
  "invalid-sasl-failure": "Invalid SASL failure",
  "invalid-bind-response": "Invalid XMPP bind response",
  "authentication-rejected": "SASL authentication failed",
  "websocket-connect-timeout": "WebSocket connection timed out",
  "websocket-write-timeout": "WebSocket write timed out",
  "iq-timeout": "XMPP IQ request timed out",
  "websocket-transport-error": "WebSocket transport error",
  "empty-transport-frame": "Empty XMPP transport frame",
  "transport-frame-too-large": "XMPP transport frame is too large",
  "invalid-transport-frame": "Invalid XMPP transport frame",
  "invalid-stream-open-to": "Invalid XMPP stream destination",
  "invalid-stream-open-from": "Invalid XMPP stream source",
  "unsupported-stream-version": "Unsupported XMPP stream version",
  "unsupported-websocket-message": "Unsupported WebSocket message type",
  "transport-closed": "XMPP transport is closed",
  "request-cancelled": "XMPP request was cancelled",
  disconnected: "XMPP session is disconnected",
  "invalid-resume-stanza": "Invalid XEP-0198 resume stanza",
  "push-registration-error": "XMPP push registration failed",
  "stanza-error": "XMPP stanza error",
};

export const WASM_DRIVER_TELEMETRY_CODES: Record<WasmDriverErrorReason, string> = {
  "core-error": "stream-core-error",
  "invalid-transport-scheme": "stream-invalid-transport-scheme",
  "missing-websocket-host": "stream-missing-websocket-host",
  "empty-resource": "stream-empty-resource",
  "empty-stanza-id": "stream-empty-stanza-id",
  "request-id-exhausted": "stream-request-id-exhausted",
  "duplicate-request": "stream-duplicate-request",
  "duplicate-stanza-correlation": "stream-duplicate-stanza-correlation",
  "unknown-request": "stream-unknown-request",
  "unknown-stanza-correlation": "stream-unknown-stanza-correlation",
  "invalid-phase-transition": "stream-invalid-phase-transition",
  "invalid-state-transition": "stream-invalid-state-transition",
  "missing-stream-feature": "stream-missing-stream-feature",
  "invalid-stream-features": "stream-invalid-features",
  "invalid-sasl-failure": "stream-invalid-sasl-failure",
  "invalid-bind-response": "stream-invalid-bind-response",
  "authentication-rejected": "stream-authentication-rejected",
  "websocket-connect-timeout": "stream-connect-timeout",
  "websocket-write-timeout": "stream-write-timeout",
  "iq-timeout": "stream-iq-timeout",
  "websocket-transport-error": "stream-transport-error",
  "empty-transport-frame": "stream-empty-transport-frame",
  "transport-frame-too-large": "stream-transport-frame-too-large",
  "invalid-transport-frame": "stream-invalid-transport-frame",
  "invalid-stream-open-to": "stream-invalid-open-to",
  "invalid-stream-open-from": "stream-invalid-open-from",
  "unsupported-stream-version": "stream-unsupported-version",
  "unsupported-websocket-message": "stream-unsupported-websocket-message",
  "transport-closed": "stream-transport-closed",
  "request-cancelled": "stream-request-cancelled",
  disconnected: "stream-disconnected",
  "invalid-resume-stanza": "stream-invalid-resume-stanza",
  "push-registration-error": "stream-push-registration-error",
  "stanza-error": "stream-stanza-error",
};

export function wasmControlErrorCondition(
  payload: WasmControlErrorPayload,
): WasmStreamErrorCondition | WasmAuthenticationCondition | undefined {
  return payload.kind === "stream-error"
    ? payload.condition
    : payload.authenticationCondition ?? undefined;
}
