# CloudNativePG Test Namespace
# ============================
#
# This manifest creates the 'cnpg-test' namespace for CloudNativePG verification tests.
# Apply this namespace BEFORE applying any PostgreSQL cluster test manifests.
#
# Usage:
#   kubectl apply -f verification/namespace.yaml
#   kubectl apply -f verification/sample-cluster.yaml
#
# Cleanup:
#   kubectl delete namespace cnpg-test
#
# =============================================================================

---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-test
  labels:
    app.kubernetes.io/name: cnpg-test
    app.kubernetes.io/component: verification
    app.kubernetes.io/part-of: cloudnative-pg
