# Gateway TLS Certificate
# =======================
#
# Explicit Certificate resource for Gateway TLS termination.
# Alternative to using Gateway annotation (cert-manager.io/cluster-issuer).
#
# This approach provides more control over certificate configuration:
# - Specify multiple domains (dnsNames)
# - Configure certificate duration and renewal
# - Use different issuers per certificate
#
# Certificate Workflow:
# 1. cert-manager creates ACME Order with Let's Encrypt
# 2. DNS01 challenge: cert-manager creates TXT record via Cloudflare API
# 3. Let's Encrypt verifies DNS record
# 4. Certificate issued and stored in Secret 'gateway-tls'
# 5. Gateway references Secret for TLS termination
#
# IMPORTANT: Update dnsNames with your actual domain(s)!
#
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: gateway-ingress
  labels:
    app.kubernetes.io/name: gateway-tls
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: gateway-api
spec:
  # Secret name where certificate will be stored
  # Must match Gateway listener certificateRefs
  secretName: gateway-tls

  # ClusterIssuer reference (created in Phase 9)
  # Use 'letsencrypt-staging' for testing to avoid rate limits
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io

  # Domain names for the certificate
  # Update with your actual domain(s)
  dnsNames:
    - waddle.social
    - "*.waddle.social"

  # Certificate duration (default: 2160h = 90 days for Let's Encrypt)
  # duration: 2160h

  # Renewal window before expiry (default: 720h = 30 days)
  # renewBefore: 720h

  # Private key algorithm (ECDSA recommended for modern browsers)
  privateKey:
    algorithm: ECDSA
    size: 256

# =============================================================================
# STAGING CERTIFICATE (for testing)
# =============================================================================
#
# Uncomment and use this for testing before production.
# Staging certificates are not trusted by browsers but avoid rate limits.
#
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: gateway-tls-staging
#   namespace: gateway-ingress
# spec:
#   secretName: gateway-tls-staging
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   dnsNames:
#     - waddle.social
#     - "*.waddle.social"
#   privateKey:
#     algorithm: ECDSA
#     size: 256
#
# =============================================================================

# =============================================================================
# TROUBLESHOOTING
# =============================================================================
#
# 1. Certificate stuck in 'Issuing':
#    kubectl describe certificate gateway-tls -n gateway-ingress
#    kubectl get challenges -A
#    kubectl describe challenge <challenge-name> -n gateway-ingress
#
# 2. DNS01 challenge failed:
#    - Check Cloudflare API token permissions (Zone:DNS:Edit)
#    - Verify TXT record creation: dig _acme-challenge.waddle.social TXT
#    - Check cert-manager logs: kubectl logs -n cert-manager -l app=cert-manager
#
# 3. Certificate expired:
#    - Delete Certificate and Secret, reapply
#    - Check cert-manager is running and healthy
#    - Verify ClusterIssuer is ready
#
# 4. Verify certificate:
#    kubectl get secret gateway-tls -n gateway-ingress -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -text -noout
#
# =============================================================================
