use jid::Jid;
use minidom::Element;
use tracing::warn;
use uuid::Uuid;
use xmpp_parsers::iq::Iq;
use xmpp_parsers::message::{Message, MessageType};

use super::types::{
    ArchivedMessage, ArchivedMucSender, ArchivedOccupantId, ArchivedRichMessage,
    ArchivedRichPayload, MamResult,
};
use super::{
    CLIENT_NS, DELAY_NS, FORWARD_NS, MAM_NS, MENTIONS_NS, MESSAGE_CORRECT_NS, MESSAGE_MODERATE_NS,
    MESSAGE_RETRACT_NS, MUC_USER_NS, OCCUPANT_ID_NS, REACTIONS_NS, REFERENCE_NS, REPLY_NS, RSM_NS,
    STANZA_ID_NS,
};

/// Build MAM result messages for each archived message.
///
/// `archive_jid` is the queried archive's address (room bare JID for
/// MUC archives, user bare JID for personal archives) and is stamped
/// as the result envelope's `from`. XEP-0313 §Security "Sender
/// Impersonation" requires clients to verify that result messages come
/// from the entity they queried and to discard unsolicited results —
/// an envelope without `from` (or with the wrong `from`) is dropped by
/// conformant clients, silently emptying room history (#1250).
///
/// `to_jid` is typed as `&jid::Jid` so the recipient address is a
/// validated value flowing in from the IQ wire-parse boundary; the
/// previous string-typed parameter forced an internal `parse()` whose
/// only failure mode was the `parse_message_jid` "unknown@invalid"
/// fallback (a hot-path data-loss bug).
pub fn build_result_messages(
    query_id: &str,
    archive_jid: &Jid,
    to_jid: &Jid,
    messages: &[ArchivedMessage],
) -> Vec<Message> {
    messages
        .iter()
        .map(|archived| build_result_message(query_id, archive_jid, to_jid, archived))
        .collect()
}

/// Build the MAM fin (completion) IQ response.
pub fn build_fin_iq(original_iq: &Iq, result: &MamResult) -> Iq {
    let fin = Element::builder("fin", MAM_NS)
        .attr(
            minidom::rxml::xml_ncname!("complete").to_owned(),
            if result.complete { "true" } else { "false" },
        )
        .append(build_rsm_response_element(result))
        .build();

    Iq::Result {
        from: original_iq.to().cloned(),
        to: original_iq.from().cloned(),
        id: original_iq.id().to_string(),
        payload: Some(fin),
    }
}

fn build_result_message(
    query_id: &str,
    archive_jid: &Jid,
    to_jid: &Jid,
    archived: &ArchivedMessage,
) -> Message {
    let inner_msg = archived_inner_message(archived);
    let delay = Element::builder("delay", DELAY_NS)
        .attr(
            minidom::rxml::xml_ncname!("stamp").to_owned(),
            archived.timestamp.to_rfc3339(),
        )
        .build();
    let forwarded = Element::builder("forwarded", FORWARD_NS)
        .append(delay)
        .append(inner_msg)
        .build();
    let result = Element::builder("result", MAM_NS)
        .attr(minidom::rxml::xml_ncname!("queryid").to_owned(), query_id)
        .attr(minidom::rxml::xml_ncname!("id").to_owned(), &archived.id)
        .append(forwarded)
        .build();

    let mut msg = Message::new(Some(to_jid.clone()));
    // XEP-0313 §Security "Sender Impersonation": the result envelope
    // MUST come from the queried archive JID so clients can match it
    // against their open query instead of discarding it as unsolicited.
    msg.from = Some(archive_jid.clone());
    msg.id = Some(xmpp_parsers::message::Id(Uuid::now_v7().to_string()));
    msg.type_ = MessageType::Normal;
    msg.payloads.push(result);
    msg
}

/// Reconstruct the inner `<message/>` for an archived row, used both
/// by the MAM `<result/>` envelope (XEP-0313 §4.2) and by adjacent
/// surfaces that need to forward an archived stanza (XEP-0430 inbox
/// `<message>` payloads embed the same shape).
///
/// Prefers the canonical archived XML when present, falls back to the
/// typed reconstruction for legacy or partial rows. Exposed as `pub`
/// so neighbouring crates can share the single source of truth for
/// "what does the forwarded inner message look like".
pub fn archived_inner_message(archived: &ArchivedMessage) -> Element {
    if let Some(stanza_xml) = archived.stanza_xml.as_deref() {
        match stanza_xml.parse::<Element>() {
            Ok(element) => return normalize_archived_inner_message(element, archived),
            Err(error) => {
                warn!(
                    archive_id = %archived.id,
                    error = %error,
                    "Failed to parse archived stanza XML, falling back to typed reconstruction"
                );
            }
        }
    }

    if let Some(rich) = archived.rich.as_ref() {
        return build_typed_inner_message(archived, rich);
    }

    build_legacy_inner_message(archived)
}

/// Wire-form name for a [`MessageType`] (the closed RFC 6121 §5.2.2
/// set: `chat`, `error`, `groupchat`, `headline`, `normal`).
///
/// `xmpp_parsers::message::MessageType` is generated by the
/// `generate_attribute! { …, Default = Normal }` macro, which
/// implements `IntoAttributeValue` (returns `None` for the default
/// to omit the attribute on serialize) and `xso::AsXmlText`, but
/// **not** `Display` — `to_string()` on the enum does not exist.
///
/// We need an unconditional wire-form string for both replay
/// (`<message type='…'/>` is always emitted with an explicit type
/// for archived rows, including the default) and SQL bind. This
/// helper provides exactly that: a total mapping from the typed
/// enum back to the same wire literal `MessageType::from_str`
/// would parse.
pub fn message_type_wire_str(message_type: &MessageType) -> &'static str {
    match message_type {
        MessageType::Chat => "chat",
        MessageType::Error => "error",
        MessageType::Groupchat => "groupchat",
        MessageType::Headline => "headline",
        MessageType::Normal => "normal",
    }
}

/// Build the room-authored XEP-0313 §MUC Archives real-JID disclosure:
/// `<x xmlns='http://jabber.org/protocol/muc#user'><item affiliation
/// role jid='real-jid'/></x>`. Used by the archive write path (baked
/// into `stanza_xml`) and by the typed fallback reconstruction below,
/// so both replay paths agree on the wire shape.
pub fn build_archived_muc_sender_x(sender: &ArchivedMucSender) -> Element {
    Element::builder("x", MUC_USER_NS)
        .append(
            Element::builder("item", MUC_USER_NS)
                .attr(
                    minidom::rxml::xml_ncname!("affiliation").to_owned(),
                    sender.affiliation.to_string(),
                )
                .attr(
                    minidom::rxml::xml_ncname!("role").to_owned(),
                    sender.role.to_string(),
                )
                .attr(
                    minidom::rxml::xml_ncname!("jid").to_owned(),
                    sender.jid.to_string(),
                )
                .build(),
        )
        .build()
}

/// Build a XEP-0421 `<occupant-id xmlns='urn:xmpp:occupant-id:0'
/// id='…'/>` element from the archived projection value.
pub fn build_archived_occupant_id_element(id: &ArchivedOccupantId) -> Element {
    Element::builder("occupant-id", OCCUPANT_ID_NS)
        .attr(minidom::rxml::xml_ncname!("id").to_owned(), id.as_str())
        .build()
}

fn normalize_archived_inner_message(element: Element, archived: &ArchivedMessage) -> Element {
    if archived.message_type != MessageType::Groupchat {
        return element;
    }

    let mut normalized = if element.attr("to").is_none() {
        element
    } else {
        let ns = element.ns().to_string();
        let name = element.name().to_string();
        let mut builder = Element::builder(name, &ns);
        for ((attr_ns, attr_name), value) in element.attrs() {
            if attr_name.as_str() != "to" {
                builder = builder.attr_ns(attr_ns.clone(), attr_name.clone(), value.clone());
            }
        }
        for child in element.children().cloned() {
            builder = builder.append(child);
        }
        builder.build()
    };

    if let Some(info) = archived.thread.as_ref() {
        crate::xep0201::install_thread_element(&mut normalized, info);
    }

    normalized
}

fn build_typed_inner_message(archived: &ArchivedMessage, rich: &ArchivedRichMessage) -> Element {
    let msg_type = archived.message_type.clone();

    let mut builder = Element::builder("message", CLIENT_NS)
        .attr(
            minidom::rxml::xml_ncname!("from").to_owned(),
            archived.from.to_string(),
        )
        .attr(
            minidom::rxml::xml_ncname!("type").to_owned(),
            message_type_wire_str(&msg_type),
        );
    if msg_type != MessageType::Groupchat {
        builder = builder.attr(
            minidom::rxml::xml_ncname!("to").to_owned(),
            archived.to.to_string(),
        );
    }

    if let Some(sid) = archived.stanza_id.as_ref() {
        builder = builder.attr(minidom::rxml::xml_ncname!("id").to_owned(), sid.id.as_str());
    }
    // RFC 6121 §5.2.4: preserve every persisted subject language
    // variant. The empty map key represents the default-language
    // `<subject/>` and therefore carries no `xml:lang` attribute.
    for (lang, text) in &rich.subjects {
        let mut subject = Element::builder("subject", CLIENT_NS);
        if !lang.is_empty() {
            subject = subject.attr_ns(
                minidom::rxml::Namespace::XML,
                minidom::rxml::xml_ncname!("lang").to_owned(),
                lang,
            );
        }
        builder = builder.append(subject.append(text.as_str()).build());
    }
    // RFC 6121 §5.2.3 / XEP-0313 §3: emit `<body/>` exactly when the
    // archived row recorded one on the wire. `Some("")` is a real
    // empty `<body></body>` element and MUST round-trip as such;
    // `None` MUST emit no `<body/>` element at all (subject-only,
    // reaction-only, and other annotation-only stanzas).
    if let Some(body) = archived.body.as_deref() {
        builder = builder.append(
            Element::builder("body", CLIENT_NS)
                .append(body.to_owned())
                .build(),
        );
    }
    // XEP-0201: emit `<thread parent='X'>id</thread>` via the canonical
    // typed builder so the optional parent attribute round-trips on
    // replay. The "parent without id ⇒ no `<thread/>` element" rule is
    // enforced at the type level by collapsing the previous two flat
    // fields into `Option<ThreadInfo>`: you cannot construct
    // [`ThreadInfo`] with a parent and no id, so a row that was
    // ever decoded into `archived.thread` already carries a coherent
    // shape. A row with no thread metadata at all is `None` and emits
    // nothing.
    if let Some(info) = archived.thread.as_ref() {
        builder = builder.append(crate::xep0201::build_thread_element(info, CLIENT_NS));
    }
    if let Some(oid) = archived.origin_id.as_ref() {
        builder = builder.append(
            Element::builder("origin-id", STANZA_ID_NS)
                .attr(minidom::rxml::xml_ncname!("id").to_owned(), oid.id.as_str())
                .build(),
        );
    }
    builder = append_reconstructed_stanza_id(builder, archived, &msg_type);
    if msg_type == MessageType::Groupchat {
        // XEP-0421 Business Rules: occupant-id MUST be attached to
        // every message sent by a MUC, including MAM history — the
        // typed fallback must not drop it just because the row lacks
        // `stanza_xml` (#1268).
        if let Some(occupant_id) = rich.occupant_id.as_ref() {
            builder = builder.append(build_archived_occupant_id_element(occupant_id));
        }
        // XEP-0313 §MUC Archives: non-anonymous rooms disclose the
        // sender's real JID via a room-authored muc#user `<x/>`.
        if let Some(sender) = rich.muc_sender.as_ref() {
            builder = builder.append(build_archived_muc_sender_x(sender));
        }
    }
    if let Some(reply) = rich.reply.as_ref() {
        let mut reply_builder = Element::builder("reply", REPLY_NS).attr(
            minidom::rxml::xml_ncname!("id").to_owned(),
            reply.id.as_str(),
        );
        if let Some(to) = reply.to.as_ref() {
            reply_builder =
                reply_builder.attr(minidom::rxml::xml_ncname!("to").to_owned(), to.to_string());
        }
        builder = builder.append(reply_builder.build());
    }
    for reference in &rich.references {
        let mut reference_builder = Element::builder("reference", REFERENCE_NS).attr(
            minidom::rxml::xml_ncname!("type").to_owned(),
            reference.ref_type.as_str(),
        );
        if let Some(begin) = reference.begin {
            reference_builder = reference_builder.attr(
                minidom::rxml::xml_ncname!("begin").to_owned(),
                begin.to_string(),
            );
        }
        if let Some(end) = reference.end {
            reference_builder = reference_builder.attr(
                minidom::rxml::xml_ncname!("end").to_owned(),
                end.to_string(),
            );
        }
        if let Some(uri) = reference.uri.as_ref() {
            reference_builder =
                reference_builder.attr(minidom::rxml::xml_ncname!("uri").to_owned(), uri.as_str());
        }
        if let Some(anchor) = reference.anchor.as_ref() {
            reference_builder = reference_builder.attr(
                minidom::rxml::xml_ncname!("anchor").to_owned(),
                anchor.as_str(),
            );
        }
        builder = builder.append(reference_builder.build());
    }
    for mention in &rich.mentions {
        let mut mention_elem = Element::builder("mention", MENTIONS_NS).build();
        if let Some(begin) = mention.begin {
            mention_elem.set_attr(
                minidom::rxml::Namespace::NONE,
                minidom::rxml::xml_ncname!("begin").to_owned(),
                begin.to_string(),
            );
        }
        if let Some(end) = mention.end {
            mention_elem.set_attr(
                minidom::rxml::Namespace::NONE,
                minidom::rxml::xml_ncname!("end").to_owned(),
                end.to_string(),
            );
        }
        if let Some(jid) = mention.jid.as_ref() {
            mention_elem.set_attr(
                minidom::rxml::Namespace::NONE,
                minidom::rxml::xml_ncname!("jid").to_owned(),
                jid.to_string(),
            );
        }
        if let Some(occupant_id) = mention.occupant_id.as_ref() {
            mention_elem.set_attr(
                minidom::rxml::Namespace::NONE,
                minidom::rxml::xml_ncname!("occupantid").to_owned(),
                occupant_id.as_str(),
            );
        }
        if let Some(mentions) = mention.mentions.as_ref() {
            mention_elem.set_attr(
                minidom::rxml::Namespace::NONE,
                minidom::rxml::xml_ncname!("mentions").to_owned(),
                mentions.as_str(),
            );
        }
        if let Some(uri) = mention.uri.as_ref() {
            mention_elem.set_attr(
                minidom::rxml::Namespace::NONE,
                minidom::rxml::xml_ncname!("uri").to_owned(),
                uri.as_str(),
            );
        }
        if mention.active {
            mention_elem.append_child(Element::builder("active", MENTIONS_NS).build());
        }
        if mention.noping {
            mention_elem.append_child(Element::builder("noping", MENTIONS_NS).build());
        }
        builder = builder.append(mention_elem);
    }

    match rich.payload.as_ref() {
        Some(ArchivedRichPayload::Correction { replaces_id }) => {
            builder = builder.append(
                Element::builder("replace", MESSAGE_CORRECT_NS)
                    .attr(
                        minidom::rxml::xml_ncname!("id").to_owned(),
                        replaces_id.as_str(),
                    )
                    .build(),
            );
        }
        Some(ArchivedRichPayload::Retraction(retraction)) => {
            let retract_builder = Element::builder("retract", MESSAGE_RETRACT_NS).attr(
                minidom::rxml::xml_ncname!("id").to_owned(),
                retraction.target_id.as_str(),
            );
            builder = builder.append(retract_builder.build());
        }
        Some(ArchivedRichPayload::Moderation(moderation)) => {
            let moderated = Element::builder("moderated", MESSAGE_MODERATE_NS)
                .attr(
                    minidom::rxml::xml_ncname!("by").to_owned(),
                    moderation.moderated_by.to_string(),
                )
                .build();
            let mut retract = Element::builder("retract", MESSAGE_RETRACT_NS)
                .attr(
                    minidom::rxml::xml_ncname!("id").to_owned(),
                    moderation.target_id.as_str(),
                )
                .append(moderated);
            if let Some(reason) = moderation.reason.as_ref() {
                retract = retract.append(
                    Element::builder("reason", MESSAGE_RETRACT_NS)
                        .append(reason.as_str())
                        .build(),
                );
            }
            builder = builder.append(retract.build());
        }
        Some(ArchivedRichPayload::Reactions(reactions)) => {
            let mut reactions_elem = Element::builder("reactions", REACTIONS_NS)
                .attr(
                    minidom::rxml::xml_ncname!("id").to_owned(),
                    reactions.target_id.as_str(),
                )
                .build();
            for emoji in &reactions.emojis {
                reactions_elem.append_child(
                    Element::builder("reaction", REACTIONS_NS)
                        .append(emoji.as_str())
                        .build(),
                );
            }
            builder = builder.append(reactions_elem);
        }
        Some(ArchivedRichPayload::Tombstone(tombstone)) => {
            let mut retracted = Element::builder("retracted", MESSAGE_RETRACT_NS).attr(
                minidom::rxml::xml_ncname!("stamp").to_owned(),
                tombstone.stamp.to_rfc3339(),
            );
            if let Some(retraction_id) = tombstone.retraction_id.as_ref() {
                retracted = retracted.attr(
                    minidom::rxml::xml_ncname!("id").to_owned(),
                    retraction_id.as_str(),
                );
            }
            if let Some(moderation) = tombstone.moderation.as_ref() {
                let moderated = Element::builder("moderated", MESSAGE_MODERATE_NS)
                    .attr(
                        minidom::rxml::xml_ncname!("by").to_owned(),
                        moderation.moderated_by.to_string(),
                    )
                    .build();
                retracted = retracted.append(moderated);
                if let Some(reason) = moderation.reason.as_ref() {
                    retracted = retracted.append(
                        Element::builder("reason", MESSAGE_RETRACT_NS)
                            .append(reason.as_str())
                            .build(),
                    );
                }
            }
            builder = builder.append(retracted.build());
        }
        None => {}
    }

    builder.build()
}

fn build_legacy_inner_message(archived: &ArchivedMessage) -> Element {
    let msg_type = archived.message_type.clone();

    let mut builder = Element::builder("message", CLIENT_NS)
        .attr(
            minidom::rxml::xml_ncname!("from").to_owned(),
            archived.from.to_string(),
        )
        .attr(
            minidom::rxml::xml_ncname!("type").to_owned(),
            message_type_wire_str(&msg_type),
        );
    if msg_type != MessageType::Groupchat {
        builder = builder.attr(
            minidom::rxml::xml_ncname!("to").to_owned(),
            archived.to.to_string(),
        );
    }

    if let Some(sid) = archived.stanza_id.as_ref() {
        builder = builder.attr(minidom::rxml::xml_ncname!("id").to_owned(), sid.id.as_str());
    }
    // RFC 6121 §5.2.3 / XEP-0313 §3: see `build_typed_inner_message`
    // — `Some("")` round-trips as `<body></body>`, `None` omits the
    // element entirely.
    if let Some(body) = archived.body.as_deref() {
        builder = builder.append(
            Element::builder("body", CLIENT_NS)
                .append(body.to_owned())
                .build(),
        );
    }
    // XEP-0201: same emission rule as `build_typed_inner_message`. Use
    // the canonical typed builder so parent round-trips. The "parent
    // without id" incoherence (RFC 6121 §5.2.5) is unrepresentable in
    // [`ThreadInfo`], so emission is simply gated on the entire
    // `archived.thread` being `Some`.
    if let Some(info) = archived.thread.as_ref() {
        builder = builder.append(crate::xep0201::build_thread_element(info, CLIENT_NS));
    }
    if let Some(reply) = archived.reply.as_ref() {
        let mut reply_builder = Element::builder("reply", REPLY_NS).attr(
            minidom::rxml::xml_ncname!("id").to_owned(),
            reply.id.as_str(),
        );
        if let Some(to) = reply.to.as_ref() {
            reply_builder =
                reply_builder.attr(minidom::rxml::xml_ncname!("to").to_owned(), to.to_string());
        }
        builder = builder.append(reply_builder.build());
    }
    if let Some(oid) = archived.origin_id.as_ref() {
        builder = builder.append(
            Element::builder("origin-id", STANZA_ID_NS)
                .attr(minidom::rxml::xml_ncname!("id").to_owned(), oid.id.as_str())
                .build(),
        );
    }
    builder = append_reconstructed_stanza_id(builder, archived, &msg_type);

    builder.build()
}

/// Append the XEP-0359 `<stanza-id/>` to a reconstructed (fallback)
/// inner message.
///
/// - **Groupchat** rows stamp `by` = the room JID (`archived.to`).
/// - **1:1** rows stamp the archive row's canonical XEP-0359 id
///   (`archived.id` — the value the live-delivered copy carried in its
///   `<stanza-id/>` per XEP-0359 §3), attributed to the archive owner
///   (`archived.stanza_id.by`, reconstructed from the archive JID at
///   decode time). NOTE: `archived.stanza_id.id` is the message's WIRE
///   id, not the archive id — emitting it here would advertise an id
///   no client can correlate with the live copy. A reconstruction
///   without any stanza-id left legacy 1:1 rows un-dedupable against
///   live copies (#1266 item 8). Rows persisted with `stanza_xml`
///   already carry the stamp inline and never reach this fallback.
fn append_reconstructed_stanza_id(
    builder: minidom::ElementBuilder,
    archived: &ArchivedMessage,
    msg_type: &MessageType,
) -> minidom::ElementBuilder {
    if archived.id.is_empty() {
        return builder;
    }
    if *msg_type == MessageType::Groupchat {
        return builder.append(
            Element::builder("stanza-id", STANZA_ID_NS)
                .attr(minidom::rxml::xml_ncname!("id").to_owned(), &archived.id)
                .attr(
                    minidom::rxml::xml_ncname!("by").to_owned(),
                    archived.to.to_string(),
                )
                .build(),
        );
    }
    // The archive owner's JID is only recorded on the row via the
    // decode-reconstructed `stanza_id.by`; without it there is no
    // trustworthy `by` to attribute (XEP-0359 §3 makes `by` REQUIRED),
    // so emit nothing rather than fabricate an attribution.
    let Some(sid) = archived.stanza_id.as_ref() else {
        return builder;
    };
    builder.append(
        Element::builder("stanza-id", STANZA_ID_NS)
            .attr(minidom::rxml::xml_ncname!("id").to_owned(), &archived.id)
            .attr(
                minidom::rxml::xml_ncname!("by").to_owned(),
                sid.by.to_string(),
            )
            .build(),
    )
}

fn build_rsm_response_element(result: &MamResult) -> Element {
    let mut builder = Element::builder("set", RSM_NS);

    if let Some(first) = result.first_id.as_deref() {
        builder = builder.append(Element::builder("first", RSM_NS).append(first).build());
    }
    if let Some(last) = result.last_id.as_deref() {
        builder = builder.append(Element::builder("last", RSM_NS).append(last).build());
    }
    if let Some(count) = result.count {
        builder = builder.append(
            Element::builder("count", RSM_NS)
                .append(count.to_string())
                .build(),
        );
    }

    builder.build()
}
