apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/platform/apps
  prune: true
  dependsOn:
    - name: infra-cloudnative-pg
    - name: infra-spicedb-operator
    - name: infra-onepassword-connect
    - name: infra-cilium-gateway
