apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: waddle-r2-credentials
  namespace: waddle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: waddle-r2-credentials
    creationPolicy: Owner
  data:
    - secretKey: WADDLE_S3_ACCESS_KEY_ID
      remoteRef:
        key: waddle-server-files
        property: s3-credentials.access-key-id
    - secretKey: WADDLE_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: waddle-server-files
        property: s3-credentials.secret-access-key
