apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql-cluster.yaml
  - postgresql-monitoring-ingress.yaml
  - spicedb-postgres-app-user-external-secret.yaml
  - spicedb-config-external-secret.yaml
  - spicedb-postgres-cluster.yaml
  - spicedb-cluster.yaml
  - xmpp-certificate.yaml
  - runtime-external-secret.yaml
  - openrouter-external-secret.yaml
  - livekit-external-secret.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - httproute-http-redirect.yaml
  - reference-grant.yaml
