apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: waddle-livekit-credentials
  namespace: waddle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: waddle-livekit-credentials
    creationPolicy: Owner
  data:
    - secretKey: WADDLE_LIVEKIT_API_KEY
      remoteRef:
        key: livekit-sfu
        property: api-key
    - secretKey: WADDLE_LIVEKIT_API_SECRET
      remoteRef:
        key: livekit-sfu
        property: api-secret
    - secretKey: WADDLE_LIVEKIT_TURN_SHARED_SECRET
      remoteRef:
        key: livekit-sfu
        property: turn-shared-secret
