apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: waddle-openrouter
  namespace: waddle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: waddle-openrouter
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          reconcile.fluxcd.io/watch: "Enabled"
      data:
        api_key: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: server-runtime-production
        property: openrouter-api-key
