apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: waddle
spec:
  instances: 2

  bootstrap:
    initdb:
      database: waddle
      owner: waddle

  monitoring:
    customQueriesConfigMap:
      - name: postgresql-monitoring-ingress
        key: queries
    disableDefaultQueries: false

  storage:
    size: 10Gi
    storageClass: openebs-mayastor

  walStorage:
    size: 2Gi
    storageClass: openebs-mayastor

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
