apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: waddle
spec:
  instances: 2

  bootstrap:
    initdb:
      database: waddle
      owner: waddle

  storage:
    size: 10Gi
    storageClass: openebs-mayastor

  walStorage:
    size: 2Gi
    storageClass: openebs-mayastor

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://waddle-postgres-backups/
      endpointURL: https://f90cc3950ab5b356ec869fe64c867ea7.r2.cloudflarestorage.com
      serverName: postgresql
      s3Credentials:
        accessKeyId:
          name: postgres-backup-r2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: postgres-backup-r2-credentials
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
