apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spicedb-config
  namespace: waddle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: spicedb-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        datastore_uri: >-
          postgresql://{{ .postgres_username | urlquery }}:{{ .postgres_password | urlquery }}@postgresql-spicedb-rw:5432/spicedb?sslmode=disable
        preshared_key: "{{ .preshared_key }}"
  data:
    - secretKey: postgres_username
      remoteRef:
        key: spicedb
        property: postgres-username
    - secretKey: postgres_password
      remoteRef:
        key: spicedb
        property: postgres-password
    - secretKey: preshared_key
      remoteRef:
        key: server-runtime-production
        property: spicedb-preshared-key
