apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spicedb-postgres-app-user
  namespace: waddle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: spicedb-postgres-app-user
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .postgres_username }}"
        password: "{{ .postgres_password }}"
  data:
    - secretKey: postgres_username
      remoteRef:
        key: spicedb
        property: postgres-username
    - secretKey: postgres_password
      remoteRef:
        key: spicedb
        property: postgres-password
