apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: waddle-spicedb
  namespace: waddle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: waddle-spicedb
    creationPolicy: Owner
  data:
    - secretKey: WADDLE_SPICEDB_PRESHARED_KEY
      remoteRef:
        key: spicedb
        property: preshared-key
