apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-spicedb
  namespace: waddle
spec:
  instances: 1
  bootstrap:
    initdb:
      database: spicedb
      owner: spicedb
      secret:
        name: spicedb-postgres-app-user
  storage:
    size: 10Gi
    storageClass: openebs-mayastor
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://waddle-postgres-backups/postgresql-spicedb/
      endpointURL: https://f90cc3950ab5b356ec869fe64c867ea7.r2.cloudflarestorage.com
      serverName: postgresql-spicedb
      s3Credentials:
        accessKeyId:
          name: postgres-backup-r2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: postgres-backup-r2-credentials
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
