# Proxmox CSI Credentials Secret Template
# ========================================
#
# PREREQUISITES:
# --------------
# The namespace 'csi-proxmox' must exist before applying this Secret.
# Create it with:
#   kubectl create namespace csi-proxmox
#
# SECURITY WARNING:
# -----------------
# This is a TEMPLATE file. Do NOT commit this file with real credentials!
# The actual credentials should be created using kubectl directly.
#
# =============================================================================
# ENVIRONMENT VARIABLE REFERENCE
# =============================================================================
# The values in this Secret should be derived from the PROXMOX_CSI_* variables
# in infrastructure/.env.example. Use these as the canonical source:
#
#   PROXMOX_CSI_ENDPOINT   -> url (append /api2/json, e.g., https://host:8006/api2/json)
#   PROXMOX_CSI_TOKEN_ID   -> token_id (e.g., kubernetes-csi@pve!csi)
#   PROXMOX_CSI_INSECURE   -> insecure (true/false)
#   PROXMOX_CSI_REGION     -> region (e.g., proxmox)
#
# This ensures consistency between VM provisioning and CSI driver configuration.
# =============================================================================
#
# RECOMMENDED: Create the secret from a local file:
#
#   1. Create a local config file (DO NOT commit this file):
#
#      cat > proxmox-csi-config.yaml <<EOF
#      clusters:
#        - url: https://proxmox.waddle.social:8006/api2/json
#          insecure: false
#          token_id: "kubernetes-csi@pve!csi"
#          token_secret: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#          region: proxmox
#      EOF
#
#   2. Create the Kubernetes secret:
#
#      kubectl create namespace csi-proxmox
#      kubectl create secret generic proxmox-csi-credentials \
#        --from-file=config.yaml=proxmox-csi-config.yaml \
#        -n csi-proxmox
#
#   3. Delete the local file immediately:
#
#      rm proxmox-csi-config.yaml
#
# For production environments, use sealed-secrets or external-secrets
# instead of storing credentials in Git.
#
# =============================================================================
# CONFIGURATION NOTES
# =============================================================================
#
# url: Proxmox API endpoint (derived from PROXMOX_CSI_ENDPOINT + /api2/json)
#      Format: https://<proxmox-host>:8006/api2/json
#
# insecure: Set to true ONLY for self-signed certificates (not recommended)
#           For production, use valid TLS certificates
#           Derived from PROXMOX_CSI_INSECURE in .env
#
# token_id: API token ID from 'pveum user token add' command
#           Format: <user>@<realm>!<tokenid>
#           Derived from PROXMOX_CSI_TOKEN_ID in .env
#           Example: kubernetes-csi@pve!csi
#
# token_secret: The UUID token secret shown only once when creating the token
#               Example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
#               NOTE: This is NOT stored in .env for security reasons
#
# region: Topology region for volume placement
#         Derived from PROXMOX_CSI_REGION in .env
#         Should match TALOS_TOPOLOGY_REGION for consistency
#
# =============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-credentials
  namespace: csi-proxmox
  labels:
    app.kubernetes.io/name: proxmox-csi
    app.kubernetes.io/component: credentials
type: Opaque
stringData:
  # REPLACE ALL PLACEHOLDER VALUES BEFORE APPLYING
  # This uses stringData for readability - Kubernetes will base64 encode automatically
  #
  # Derive these values from infrastructure/.env.example:
  #   url         = PROXMOX_CSI_ENDPOINT + "/api2/json"
  #   insecure    = PROXMOX_CSI_INSECURE
  #   token_id    = PROXMOX_CSI_TOKEN_ID
  #   region      = PROXMOX_CSI_REGION
  config.yaml: |
    clusters:
      - url: https://proxmox.waddle.social:8006/api2/json
        insecure: false
        token_id: "kubernetes-csi@pve!csi"
        token_secret: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        region: proxmox

# =============================================================================
# MULTI-CLUSTER CONFIGURATION
# =============================================================================
#
# For multiple Proxmox clusters or hosts, add additional entries:
#
#   config.yaml: |
#     clusters:
#       - url: https://proxmox1.waddle.social:8006/api2/json
#         insecure: false
#         token_id: "kubernetes-csi@pve!csi"
#         token_secret: "token-for-cluster-1"
#         region: dc1
#       - url: https://proxmox2.waddle.social:8006/api2/json
#         insecure: false
#         token_id: "kubernetes-csi@pve!csi"
#         token_secret: "token-for-cluster-2"
#         region: dc2
#
# =============================================================================
