# Proxmox CSI StorageClass (Standalone Manifest)
# ==============================================
#
# IMPORTANT: MUTUAL EXCLUSIVITY WITH HELM-MANAGED STORAGECLASS
# ------------------------------------------------------------
# This manifest creates a STANDALONE StorageClass for Proxmox CSI volumes.
# It is MUTUALLY EXCLUSIVE with the Helm chart's StorageClass.
#
# CHOOSE ONE OPTION:
#
#   OPTION A: Use Helm-managed StorageClass (recommended)
#   -----------------------------------------------------
#   - Keep 'storageClass' array populated in helm-values.yaml
#   - Do NOT apply this manifest
#   - StorageClass is managed by Helm lifecycle
#
#   OPTION B: Use this standalone manifest
#   ---------------------------------------
#   - Set 'storageClass: []' (empty array) in helm-values.yaml
#   - Apply this manifest: kubectl apply -f storageclass.yaml
#   - StorageClass is managed independently
#
# DO NOT USE BOTH OPTIONS SIMULTANEOUSLY!
# This would create duplicate StorageClass/proxmox-csi definitions and
# potentially conflicting default StorageClass annotations.
#
# If you need to switch from Helm-managed to standalone (or vice versa):
#   1. Delete the existing StorageClass: kubectl delete storageclass proxmox-csi
#   2. Update helm-values.yaml accordingly
#   3. Redeploy the Helm chart or apply this manifest
#
# =============================================================================

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-csi
  labels:
    app.kubernetes.io/name: proxmox-csi
    app.kubernetes.io/component: storage
  annotations:
    # Make this the default StorageClass
    # WARNING: Only one StorageClass should be marked as default
    storageclass.kubernetes.io/is-default-class: "true"

# CSI driver provisioner name
provisioner: csi.proxmox.sinextra.dev

# StorageClass parameters passed to the CSI driver
parameters:
  # Proxmox storage ID (must match a valid storage backend in Proxmox)
  # Use 'pvesm status' on Proxmox host to list available storage
  # Common values: 'local-lvm', 'local-zfs', 'ceph-pool', 'nfs-storage'
  storage: local-lvm

  # Disk cache mode
  # Options:
  #   - directsync: Safest mode, writes go directly to disk (slowest)
  #   - writethrough: Writes cached but sync'd immediately (balanced)
  #   - writeback: Writes cached, async sync (fastest but risky)
  #   - none: Let the storage backend decide
  # Recommendation: Use 'writethrough' for general workloads,
  #                 'directsync' for databases
  cache: writethrough

  # Mark storage as SSD (affects I/O scheduler in guest OS)
  # Set to "true" if your Proxmox storage backend uses SSDs
  ssd: "false"

  # Filesystem type for new volumes
  # Options: ext4 (recommended), xfs
  # fstype: ext4

# What happens to volumes when PVC is deleted
# Options:
#   - Delete: Volume is automatically deleted (default)
#   - Retain: Volume is kept for manual cleanup/recovery
reclaimPolicy: Delete

# When to bind PVC to PV
# Options:
#   - WaitForFirstConsumer: Delay binding until pod is scheduled
#     (enables topology-aware placement, recommended)
#   - Immediate: Bind immediately when PVC is created
volumeBindingMode: WaitForFirstConsumer

# Volume expansion (resize) support
# NOTE: Not supported by Proxmox CSI driver v0.13.0
allowVolumeExpansion: false

# =============================================================================
# EXAMPLE: Additional StorageClass for SSD Storage
# =============================================================================
#
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: proxmox-csi-fast
#   labels:
#     app.kubernetes.io/name: proxmox-csi
#     app.kubernetes.io/component: storage
# provisioner: csi.proxmox.sinextra.dev
# parameters:
#   storage: local-nvme    # NVMe-backed storage pool
#   cache: writeback       # Faster cache mode for SSDs
#   ssd: "true"
# reclaimPolicy: Delete
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: false
#
# =============================================================================
# EXAMPLE: StorageClass for Database Workloads (Maximum Safety)
# =============================================================================
#
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: proxmox-csi-safe
#   labels:
#     app.kubernetes.io/name: proxmox-csi
#     app.kubernetes.io/component: storage
# provisioner: csi.proxmox.sinextra.dev
# parameters:
#   storage: local-lvm
#   cache: directsync      # Safest cache mode
#   ssd: "false"
# reclaimPolicy: Retain    # Keep volumes on PVC deletion
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: false
#
# =============================================================================
