apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull
  namespace: waddle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghcr-pull
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf \"%s:%s\" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: ghcr-pull
        property: username
    - secretKey: password
      remoteRef:
        key: ghcr-pull
        property: credential
