# Cloudflare API Token Secret Template
# =====================================
#
# PREREQUISITES:
# --------------
# The namespace 'cert-manager' must exist before applying this Secret.
# Create it with:
#   kubectl create namespace cert-manager
#
# SECURITY WARNING:
# -----------------
# This is a TEMPLATE file. Do NOT commit this file with real credentials!
# The actual credentials should be created using kubectl directly.
#
# =============================================================================
# ENVIRONMENT VARIABLE REFERENCE
# =============================================================================
# The Cloudflare API token is referenced in .env.example but NOT stored there.
# It should only exist in the Kubernetes Secret.
#
# For documentation purposes:
#   CLOUDFLARE_API_TOKEN  -> api-token field in this Secret
#
# =============================================================================
#
# RECOMMENDED: Create the secret using kubectl (NOT from this file):
#
#   1. Create a Cloudflare API token at https://dash.cloudflare.com/profile/api-tokens:
#      - Click "Create Token"
#      - Use "Edit zone DNS" template or create custom token
#      - Permissions: Zone > DNS > Edit
#      - Zone Resources: Include > All zones (or specific zone)
#      - Copy the token (shown only once!)
#
#   2. Create the namespace (if not exists):
#      kubectl create namespace cert-manager
#
#   3. Create the Kubernetes secret:
#      kubectl create secret generic cloudflare-api-token \
#        --from-literal=api-token=<your-cloudflare-api-token> \
#        -n cert-manager
#
#   4. Verify the secret was created:
#      kubectl get secret cloudflare-api-token -n cert-manager
#
#   5. Delete any local copies of the token immediately!
#
# For production environments, use sealed-secrets or external-secrets
# instead of storing credentials in Git.
#
# =============================================================================
# API TOKEN PERMISSIONS
# =============================================================================
#
# Required permissions for DNS01 challenge solver:
#
#   Zone > DNS > Edit
#
# Recommended zone resources configuration:
#
#   - Option A (broad access): Include > All zones
#     Use this if you want cert-manager to manage certificates for any domain
#
#   - Option B (restricted access): Include > Specific zone > waddle.social
#     Use this for least-privilege access to a single domain
#
# =============================================================================
# TOKEN VERIFICATION
# =============================================================================
#
# Test your API token before creating the secret:
#
#   curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
#     -H "Authorization: Bearer <your-cloudflare-api-token>" \
#     -H "Content-Type: application/json"
#
# Expected response:
#   {"result":{"id":"...","status":"active"},"success":true,...}
#
# =============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cloudflare-credentials
type: Opaque
stringData:
  # REPLACE THIS PLACEHOLDER VALUE BEFORE APPLYING
  # This uses stringData for readability - Kubernetes will base64 encode automatically
  api-token: "<your-cloudflare-api-token>"

# =============================================================================
# MULTI-ZONE CONFIGURATION
# =============================================================================
#
# For multiple Cloudflare accounts or zones with different tokens, create
# additional secrets with unique names:
#
#   kubectl create secret generic cloudflare-api-token-zone1 \
#     --from-literal=api-token=<token-for-zone1> \
#     -n cert-manager
#
#   kubectl create secret generic cloudflare-api-token-zone2 \
#     --from-literal=api-token=<token-for-zone2> \
#     -n cert-manager
#
# Then reference the appropriate secret in each ClusterIssuer:
#
#   spec:
#     acme:
#       solvers:
#         - dns01:
#             cloudflare:
#               apiTokenSecretRef:
#                 name: cloudflare-api-token-zone1  # or zone2
#                 key: api-token
#
# =============================================================================
