apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-waddle-social-tls
  namespace: default
spec:
  secretName: chat-waddle-social-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - chat.waddle.social
