apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-tls
  namespace: default
spec:
  secretName: apps-wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.apps.waddle.social"
