# Test Certificate for cert-manager Verification
# ===============================================
#
# PURPOSE:
# This Certificate resource tests that cert-manager and the ClusterIssuer
# are properly configured. It requests a certificate from Let's Encrypt
# staging environment to verify the DNS01 challenge flow works.
#
# IMPORTANT: Replace 'test.waddle.social' with a domain YOU control in Cloudflare!
#
# =============================================================================
# USAGE
# =============================================================================
#
# 1. Edit this file and replace 'test.waddle.social' with your actual domain
#    that is managed by Cloudflare.
#
# 2. Apply the test certificate:
#    kubectl apply -f test-certificate.yaml
#
# 3. Monitor certificate status:
#    kubectl get certificate test-certificate -n cert-manager -w
#
# 4. Check certificate events:
#    kubectl describe certificate test-certificate -n cert-manager
#
# 5. Verify the TLS secret was created:
#    kubectl get secret test-certificate-tls -n cert-manager
#
# 6. View certificate details:
#    kubectl get secret test-certificate-tls -n cert-manager -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -noout -text
#
# 7. Cleanup after testing:
#    kubectl delete -f test-certificate.yaml
#
# =============================================================================

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: test
spec:
  # Name of the Secret to store the TLS certificate
  secretName: test-certificate-tls

  # Reference to the ClusterIssuer
  # Use staging for testing to avoid rate limits
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

  # Certificate validity duration (default: 90 days)
  duration: 2160h  # 90 days

  # Renew 30 days before expiry
  renewBefore: 720h  # 30 days

  # Subject fields (optional)
  subject:
    organizations:
      - "Test Organization"

  # Private key configuration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  # IMPORTANT: Replace with a domain you control in Cloudflare!
  dnsNames:
    - test.waddle.social

# =============================================================================
# EXPECTED CERTIFICATE FLOW
# =============================================================================
#
# 1. cert-manager creates a CertificateRequest
# 2. CertificateRequest creates an Order with Let's Encrypt
# 3. Order creates a Challenge for each domain
# 4. Challenge triggers DNS01 solver:
#    - cert-manager creates _acme-challenge.test.waddle.social TXT record in Cloudflare
#    - Let's Encrypt verifies the TXT record
#    - cert-manager deletes the TXT record
# 5. Certificate is issued and stored in the Secret
#
# =============================================================================
# TROUBLESHOOTING
# =============================================================================
#
# Certificate stuck in "Issuing" or "Pending":
#
#   1. Check CertificateRequest:
#      kubectl get certificaterequest -n cert-manager
#      kubectl describe certificaterequest <name> -n cert-manager
#
#   2. Check Order:
#      kubectl get order -n cert-manager
#      kubectl describe order <name> -n cert-manager
#
#   3. Check Challenge:
#      kubectl get challenge -n cert-manager
#      kubectl describe challenge <name> -n cert-manager
#
#   4. Check cert-manager logs:
#      kubectl logs -n cert-manager -l app.kubernetes.io/component=controller --tail=100
#
# Common issues:
#
#   - "dial tcp: lookup _acme-challenge.xxx: no such host"
#     -> DNS propagation delay, wait 1-2 minutes and retry
#
#   - "DNS record not found"
#     -> Cloudflare API token doesn't have permission for this zone
#
#   - "Timeout during connect"
#     -> Cloudflare API connectivity issue, check network/firewall
#
#   - "rate limit exceeded"
#     -> Hit Let's Encrypt rate limits, wait or use different domain
#
# =============================================================================
# STAGING CERTIFICATE NOTES
# =============================================================================
#
# Certificates from Let's Encrypt staging:
#   - Are NOT trusted by browsers (you'll see certificate warnings)
#   - Are signed by "Fake LE Intermediate X1" (vs "R3" for production)
#   - Have the same structure as production certificates
#   - Are useful for testing the entire flow without rate limit concerns
#
# After successful staging test, update your Certificate to use:
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#
# =============================================================================
