apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spicedb-preshared-key
  namespace: spicedb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: spicedb-preshared-key
    creationPolicy: Owner
  data:
    - secretKey: SPICEDB_GRPC_PRESHARED_KEY
      remoteRef:
        key: spicedb-preshared-key
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-superuser
  namespace: spicedb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cnpg-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: cnpg-superuser
        property: username
    - secretKey: password
      remoteRef:
        key: cnpg-superuser
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scaleway-s3-creds
  namespace: spicedb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: scaleway-s3-creds
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: scaleway-s3-credentials
        property: access-key
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: scaleway-s3-credentials
        property: secret-key
