apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret-postgres.yaml
  - external-secret-config.yaml
  - postgres-cluster.yaml
  - spicedb-cluster.yaml
