#!/usr/bin/env bash
set -euo pipefail

root="$(git rev-parse --show-toplevel)"

cd "${root}"
cuenv sync ci -A
"${root}/server/scripts/pin-generated-github-actions.sh"

expected_generated_workflows="$(
  cat <<'WORKFLOWS'
waddle-chat-default.yml
waddle-chat-pullrequest.yml
waddle-cloud-default.yml
waddle-colony-default.yml
waddle-colony-pullrequest.yml
waddle-server-default.yml
waddle-server-githubenricher.yml
waddle-server-githubenricherpullrequest.yml
waddle-server-publish-tags-to-flakehub.yml
waddle-server-pullrequest.yml
waddle-server-xmppcompliance.yml
waddle-server-xmppcompliancepullrequest.yml
waddle-website-default.yml
waddle-website-pullrequest.yml
WORKFLOWS
)"

actual_generated_workflows="$(
  find .github/workflows -maxdepth 1 -type f -name '*.yml' -print0 |
    xargs -0 grep -l '^# Generated by cuenv' |
    sed 's#.*/##' |
    sort
)"

if [ "${actual_generated_workflows}" != "${expected_generated_workflows}" ]; then
  echo "Cuenv-generated workflow set is stale or unexpected." >&2
  echo "Expected:" >&2
  printf '%s\n' "${expected_generated_workflows}" >&2
  echo "Actual:" >&2
  printf '%s\n' "${actual_generated_workflows}" >&2
  exit 1
fi

git diff --exit-code -- .github/workflows
