apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.12.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
  values:
    installCRDs: true
    replicaCount: 1
