# Let's Encrypt Production ClusterIssuer
# =======================================
#
# PURPOSE:
# This ClusterIssuer issues PRODUCTION certificates that are trusted by
# all major browsers. Use this for production workloads only.
#
# IMPORTANT: Test with letsencrypt-staging ClusterIssuer FIRST to avoid
# hitting rate limits during development and testing.
#
# =============================================================================
# RATE LIMITS (Production)
# =============================================================================
#
# Let's Encrypt enforces strict rate limits:
#
#   - 50 certificates per registered domain per week
#   - 5 duplicate certificates per week
#   - 300 pending authorizations per account
#   - 3,000 renewal requests per account per 3 hours
#
# To avoid rate limit issues:
#   1. Always test with staging first
#   2. Use wildcard certificates (*.waddle.social) to reduce certificate count
#   3. Batch certificate requests when possible
#   4. Use certificate renewal (same domains) instead of new certificates
#
# =============================================================================
# PREREQUISITES
# =============================================================================
#
# 1. cert-manager must be installed and running
# 2. Cloudflare API token secret must exist:
#    kubectl create secret generic cloudflare-api-token \
#      --from-literal=api-token=<your-token> \
#      -n cert-manager
# 3. Test with letsencrypt-staging first to verify DNS01 solver works
#
# =============================================================================
# ENVIRONMENT VARIABLE REFERENCE
# =============================================================================
#
# Update the email address below with your value from infrastructure/.env.example:
#   CERT_MANAGER_EMAIL  -> spec.acme.email
#
# You can reuse TELEPORT_LETSENCRYPT_EMAIL if already configured.
# Let's Encrypt will send certificate expiration warnings to this email.
#
# =============================================================================

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: clusterissuer
spec:
  acme:
    # Let's Encrypt PRODUCTION ACME server
    # Certificates from production ARE trusted by browsers
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email address for certificate expiration notifications
    # REPLACE with your actual email (from CERT_MANAGER_EMAIL or TELEPORT_LETSENCRYPT_EMAIL)
    email: admin@waddle.social

    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production

    # DNS01 challenge solver using Cloudflare
    solvers:
      - dns01:
          cloudflare:
            # Reference to the Cloudflare API token secret
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token

# =============================================================================
# USAGE EXAMPLE
# =============================================================================
#
# Create a production Certificate using this issuer:
#
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: waddle-social-tls
#   namespace: default
# spec:
#   secretName: waddle-social-tls
#   issuerRef:
#     name: letsencrypt-production  # <-- References this ClusterIssuer
#     kind: ClusterIssuer
#   dnsNames:
#     - waddle.social
#     - www.waddle.social
#
# =============================================================================
# WILDCARD CERTIFICATE EXAMPLE
# =============================================================================
#
# Wildcard certificates are useful to reduce certificate count:
#
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-waddle-social
#   namespace: default
# spec:
#   secretName: wildcard-waddle-social-tls
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   dnsNames:
#     - "*.waddle.social"      # Wildcard for all subdomains
#     - "waddle.social"        # Root domain (wildcard doesn't cover this)
#
# =============================================================================
# CERTIFICATE LIFECYCLE
# =============================================================================
#
# - Certificates are valid for 90 days
# - cert-manager renews certificates at 60 days (30 days before expiry)
# - Renewal is automatic - no manual intervention needed
# - If renewal fails, cert-manager retries with exponential backoff
#
# Monitor certificate status:
#   kubectl get certificates -A
#   kubectl describe certificate <name> -n <namespace>
#
# =============================================================================
# VERIFICATION
# =============================================================================
#
# After applying this ClusterIssuer, verify it's ready:
#
#   kubectl get clusterissuer letsencrypt-production
#   kubectl describe clusterissuer letsencrypt-production
#
# Expected status:
#   Status:
#     Conditions:
#       Type:    Ready
#       Status:  True
#
# =============================================================================
