# Let's Encrypt Staging ClusterIssuer
# ====================================
#
# PURPOSE:
# This ClusterIssuer is used for TESTING certificate issuance without
# hitting Let's Encrypt production rate limits. Staging certificates are
# NOT trusted by browsers but are functionally identical to production.
#
# USAGE:
# Always test with staging first, then switch to production ClusterIssuer.
#
# RATE LIMITS (Staging):
# - 30,000 certificates per registered domain per week
# - 30,000 new orders per account per 3 hours
# - Much more lenient than production for testing
#
# =============================================================================
# PREREQUISITES
# =============================================================================
#
# 1. cert-manager must be installed and running
# 2. Cloudflare API token secret must exist:
#    kubectl create secret generic cloudflare-api-token \
#      --from-literal=api-token=<your-token> \
#      -n cert-manager
#
# =============================================================================
# ENVIRONMENT VARIABLE REFERENCE
# =============================================================================
#
# Update the email address below with your value from infrastructure/.env.example:
#   CERT_MANAGER_EMAIL  -> spec.acme.email
#
# You can reuse TELEPORT_LETSENCRYPT_EMAIL if already configured.
#
# =============================================================================

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: clusterissuer
spec:
  acme:
    # Let's Encrypt STAGING ACME server
    # Certificates from staging are NOT trusted by browsers
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address for certificate expiration notifications
    # REPLACE with your actual email (from CERT_MANAGER_EMAIL or TELEPORT_LETSENCRYPT_EMAIL)
    email: admin@waddle.social

    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # DNS01 challenge solver using Cloudflare
    solvers:
      - dns01:
          cloudflare:
            # Reference to the Cloudflare API token secret
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token

# =============================================================================
# USAGE EXAMPLE
# =============================================================================
#
# Create a test Certificate using this staging issuer:
#
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: test-certificate
#   namespace: default
# spec:
#   secretName: test-certificate-tls
#   issuerRef:
#     name: letsencrypt-staging     # <-- References this ClusterIssuer
#     kind: ClusterIssuer
#   dnsNames:
#     - test.waddle.social
#
# =============================================================================
# VERIFICATION
# =============================================================================
#
# After applying this ClusterIssuer, verify it's ready:
#
#   kubectl get clusterissuer letsencrypt-staging
#   kubectl describe clusterissuer letsencrypt-staging
#
# Expected status:
#   Status:
#     Conditions:
#       Type:    Ready
#       Status:  True
#
# If not ready, check cert-manager logs:
#   kubectl logs -n cert-manager -l app.kubernetes.io/component=controller
#
# =============================================================================
# STAGING vs PRODUCTION
# =============================================================================
#
# Staging:
#   - Certificates are NOT trusted by browsers
#   - Higher rate limits (30,000/week vs 50/week)
#   - Use for testing and development
#   - Certificate chain: Fake LE Root
#
# Production:
#   - Certificates ARE trusted by browsers
#   - Lower rate limits (50 certs/week per domain)
#   - Use for production workloads
#   - Certificate chain: ISRG Root X1
#
# =============================================================================
