[package]
name = "bench-clickhouse"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bench-core = { path = "../bench-core" }
tokio.workspace = true
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
clickhouse.workspace = true

[dev-dependencies]
testcontainers.workspace = true
testcontainers-modules.workspace = true
