apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spicedb-operator
  namespace: spicedb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: spicedb-operator
      version: "1.22.x"
      sourceRef:
        kind: HelmRepository
        name: authzed
      interval: 12h
