apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
spec:
  replicas: 1
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    storageClassName: openebs-mayastor
    resources:
      requests:
        storage: 10Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  replicas: 1
  shards: 1
  keeperClusterRef:
    name: clickhouse-keeper
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    storageClassName: openebs-mayastor
    resources:
      requests:
        storage: 50Gi
  containerTemplate:
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 4Gi
  settings:
    defaultUserPassword:
      secret:
        name: clickhouse-default-user
        key: password
    extraConfig:
      listen_host: "0.0.0.0"
