[package]
name = "waddle-extensions"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Waddle Wasm extension runtime and OCI loader"

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
futures = { workspace = true }
minidom = { workspace = true }
oci-client = "0.16"
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }
xmpp-parsers = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
