{{- if and (not .Values.apiKeys.existingSecret) (gt (len .Values.apiKeys.values) 0) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livekit-sfu.apiKeysSecretName" . }}
  labels:
    {{- include "livekit-sfu.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKeys.secretKey }}: |
{{ toYaml .Values.apiKeys.values | indent 4 }}
{{- end }}
