apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit-sfu.fullname" . }}
  labels:
    {{- include "livekit-sfu.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.livekit.prometheus_port }}
    - name: prometheus
      port: {{ .Values.livekit.prometheus_port }}
      targetPort: prometheus
      protocol: TCP
    {{- end }}
  selector:
    {{- include "livekit-sfu.selectorLabels" . | nindent 4 }}
