import { createGatewayRuntime } from "@graphql-hive/gateway-runtime";
import { createAuthPlugin } from "./auth";
import type { Env } from "./env.d.ts";
import { createServiceBindingTransport } from "./transport/service-binding";

// Import the composed supergraph SDL as text
// This file is generated by the compose script during CI/CD
import supergraphSdl from "../supergraph.graphql";

let gateway: ReturnType<typeof createGatewayRuntime>;

function getGateway(env: Env) {
	if (!gateway) {
		gateway = createGatewayRuntime({
			supergraph: supergraphSdl,
			transports: {
				http: createServiceBindingTransport(env),
			},
			plugins: () => [createAuthPlugin(env)],
			cors: {
				origin: [
					"https://waddle.social",
					"https://www.waddle.social",
					"https://colony.waddle.social",
					"https://huddle.waddle.social",
					"http://localhost:4321",
					"http://localhost:3000",
				],
				credentials: true,
				allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
			},
			graphqlEndpoint: "/",
			// Enable GraphiQL for browser access
			graphiql: true,
			landingPage: true,
			healthCheckEndpoint: "/health",
		});
	}
	return gateway;
}

export default {
	async fetch(
		request: Request,
		env: Env,
		ctx: ExecutionContext,
	): Promise<Response> {
		try {
			const runtime = getGateway(env);
			const response = await runtime(request, env, ctx);

			// Schedule cleanup without blocking response
			ctx.waitUntil(
				(async () => {
					if (runtime[Symbol.asyncDispose]) {
						await runtime[Symbol.asyncDispose]();
					}
				})(),
			);

			return response;
		} catch (error) {
			console.error("Gateway error:", error);
			return new Response(
				JSON.stringify({
					errors: [
						{
							message:
								error instanceof Error
									? error.message
									: "Internal gateway error",
						},
					],
				}),
				{
					status: 500,
					headers: { "Content-Type": "application/json" },
				},
			);
		}
	},
};
