apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.x"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 12h
  values:
    replicaCount: 1
