#!/usr/bin/env bash
# Regenerates the ignored inputs of this Apsides program, then its source lock.
# CRD versions track the operators ../gitops installs.
set -euo pipefail

cd "$(dirname "$0")"
aps="${APS:?set APS to an aps binary built from an Apsides checkout}"

# `aps init` is the only command that writes the embedded SDK and it refuses
# an existing project, so restore .aps/sdk from a throwaway scaffold.
if [[ ! -d .aps/sdk ]]; then
  scaffold="$(mktemp -d)"
  "$aps" init --directory "$scaffold/project" > /dev/null
  mkdir -p .aps
  cp -R "$scaffold/project/.aps/sdk" .aps/sdk
  rm -rf "$scaffold"
fi

crd() {
  local url=$1 kind=$2 version=$3 output=$4
  "$aps" crds fetch --url "$url" --kind "$kind" --version "$version" --output ".aps/crds/$output"
}

crd https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.25.1/config/crd/bases/postgresql.cnpg.io_clusters.yaml \
  Cluster v1 cnpg-cluster.ts
crd https://raw.githubusercontent.com/external-secrets/external-secrets/v0.12.1/config/crds/bases/external-secrets.io_externalsecrets.yaml \
  ExternalSecret v1beta1 external-secret.ts
crd https://raw.githubusercontent.com/cert-manager/cert-manager/v1.19.1/deploy/crds/cert-manager.io_certificates.yaml \
  Certificate v1 certificate.ts
crd https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.4.1/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml \
  HTTPRoute v1 httproute.ts
crd https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.4.1/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml \
  ReferenceGrant v1beta1 referencegrant.ts
crd https://raw.githubusercontent.com/authzed/spicedb-operator/v1.22.0/config/crds/authzed.com_spicedbclusters.yaml \
  SpiceDBCluster v1alpha1 spicedb-cluster.ts

# An Apsides program cannot read files while it is evaluated, so the CNPG
# monitoring queries become a module generated from the Flux ConfigMap.
mkdir -p .aps/generated
python3 - ../gitops/waddle-server/postgresql-monitoring-ingress.yaml .aps/generated/monitoring-queries.ts <<'PY'
import json, sys, yaml
queries = yaml.safe_load(open(sys.argv[1]))["data"]["queries"]
with open(sys.argv[2], "w") as out:
    out.write("// Generated by generate.sh from the Flux ConfigMap. Do not edit.\n")
    out.write(f"export const monitoringQueries = {json.dumps(queries)};\n")
PY

modules=$(find . -path ./.aps/sdk -prune -o -path ./gaps -prune -o \( -name '*.ts' -o -name '*.tsx' \) ! -name program.tsx -print | sed 's|^\./||' | sort | paste -sd, -)
"$aps" lock --source program.tsx --modules "$modules"
