# SpiceDB Namespace
# =================
#
# This namespace contains the SpiceDB authorization service and its dependencies:
# - SpiceDB operator (manages SpiceDBCluster CRDs)
# - SpiceDB cluster pods (gRPC API on port 50051)
# - Dedicated PostgreSQL cluster (CloudNativePG) for SpiceDB's datastore
#
# SpiceDB is a Google Zanzibar-inspired authorization system providing:
# - Relationship-based access control (ReBAC)
# - Consistency guarantees for permission checks
# - Schema language for defining authorization models
# - gRPC and HTTP APIs for integration
#
# Prerequisites:
# - CloudNativePG operator (Phase 11)
# - Proxmox CSI StorageClass 'proxmox-csi' (Phase 7)
# - Cilium CNI (Phase 6)
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: spicedb
  labels:
    app.kubernetes.io/name: spicedb
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: waddle-infra
