# SpiceDB Configuration Secret - REFERENCE TEMPLATE
# ==================================================
#
# IMPORTANT: This file is a REFERENCE TEMPLATE and is NOT applied by Flux.
# It is excluded from kustomization.yaml to prevent placeholder secrets
# from being deployed to the cluster.
#
# DO NOT COMMIT ACTUAL SECRETS TO GIT!
#
# =============================================================================
# SECRET CREATION OPTIONS
# =============================================================================
#
# Choose one of the following options to create the SpiceDB secret:
#
# OPTION 1: Manual Creation (Recommended for initial setup)
# ----------------------------------------------------------
#   kubectl create secret generic spicedb-config -n spicedb \
#     --from-literal=preshared_key="$(openssl rand -base64 32)" \
#     --from-literal=datastore_uri="postgres://spicedb:<PASSWORD>@spicedb-postgres-rw.spicedb.svc.cluster.local:5432/spicedb?sslmode=disable"
#
# OPTION 2: sealed-secrets (Recommended for GitOps)
# ----------------------------------------------------------
#   Create a sealed secret from this template:
#   kubeseal --format yaml < secret.yaml > sealed-secret.yaml
#   Then commit the sealed-secret.yaml to Git.
#
# OPTION 3: external-secrets
# ----------------------------------------------------------
#   Configure an ExternalSecret to fetch from Vault, AWS Secrets Manager,
#   Azure Key Vault, GCP Secret Manager, etc.
#
# OPTION 4: sops
# ----------------------------------------------------------
#   Encrypt with age/gpg:
#   sops --encrypt secret.yaml > secret.enc.yaml
#   Then commit the encrypted file to Git.
#
# =============================================================================
# SECRET GENERATION INSTRUCTIONS
# =============================================================================
#
# 1. Generate a secure preshared key (64 characters, base64 encoded):
#
#    openssl rand -base64 32
#
#    Example output: 7jK9mN2pL4qR8sT1uV6wX3yZ5aB0cD2eF4gH6iJ8kL0=
#
# 2. Get PostgreSQL password from CloudNativePG secret:
#
#    kubectl get secret spicedb-postgres-app -n spicedb -o jsonpath='{.data.password}' | base64 -d
#
# 3. Construct the datastore_uri:
#
#    postgres://spicedb:<PASSWORD>@spicedb-postgres-rw.spicedb.svc.cluster.local:5432/spicedb?sslmode=disable
#
#    Replace <PASSWORD> with the actual password from step 2.
#
# 4. Create the secret using one of the options above.
#
# =============================================================================
# SECURITY WARNINGS
# =============================================================================
#
# - NEVER commit this file with actual secret values to Git
# - Use Kubernetes RBAC to restrict access to this Secret
# - Rotate the preshared key periodically
# - The preshared key authenticates ALL SpiceDB API calls
# - If compromised, generate a new key and update all clients
#
# =============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config
  namespace: spicedb
  labels:
    app.kubernetes.io/name: spicedb
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: spicedb
type: Opaque
stringData:
  # ==========================================================================
  # preshared_key: Authentication key for SpiceDB API
  # ==========================================================================
  # All clients must provide this key to authenticate with SpiceDB.
  # Generate securely: openssl rand -base64 32
  #
  # REPLACE THIS VALUE before deployment!
  preshared_key: "REPLACE_WITH_SECURE_KEY"

  # ==========================================================================
  # datastore_uri: PostgreSQL connection string
  # ==========================================================================
  # Connection string to the PostgreSQL database managed by CloudNativePG.
  # Format: postgres://user:password@host:port/database?sslmode=disable
  #
  # Get the password from CloudNativePG secret:
  #   kubectl get secret spicedb-postgres-app -n spicedb -o jsonpath='{.data.password}' | base64 -d
  #
  # REPLACE <PASSWORD> with the actual password before deployment!
  datastore_uri: "postgres://spicedb:<PASSWORD>@spicedb-postgres-rw.spicedb.svc.cluster.local:5432/spicedb?sslmode=disable"
