# Cloudflare API Token - ExternalSecret
# ======================================
#
# Syncs the Cloudflare API token from 1Password to Kubernetes.
# Used by cert-manager for DNS01 challenges.
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: cert-manager
          app.kubernetes.io/component: cloudflare-credentials
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare
        property: api_token
