# Grafana Admin Credentials - ExternalSecret
# ===========================================
#
# Syncs the Grafana admin credentials from 1Password to Kubernetes.
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: grafana
          app.kubernetes.io/part-of: observability
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: password
