apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: livekit-sfu-api-keys
  namespace: livekit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: livekit-sfu-api-keys
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        keys.yaml: |
          {{ .apiKey }}: {{ .apiSecret | quote }}
  data:
    - secretKey: apiKey
      remoteRef:
        key: livekit-sfu
        property: api-key
    - secretKey: apiSecret
      remoteRef:
        key: livekit-sfu
        property: api-secret
